# See blockchain/connector/config/default.toml for the documentation.

tick_interval_secs = 1

[blockchain]
addresses = ["http://localhost:9090"]
asc_address = "wasm18shslphc8j358hpeqmjlxz77u6hvq5ly8dzxnkhz4266z8qyj46qq9afqf" # Deployed ASC
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

[blockchain.signkey]
mnemonic = "put movie amateur ginger invite ski twenty sentence critic suspect elder gadget rude assault metal salute stock act glass crowd jacket accident profit banana"
# bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
denom = "ucosm"
amount = 3000000

[core]
addresses = ["http://localhost:50051"]

[core.timeout_config]
channel_timeout = 60

[core.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[core.timeout_config.insecure_crs]
initial_wait_time = 1
retry_interval = 3
max_poll_count = 24

[core.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.decryption]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.reencryption]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.verify_proven_ct]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.insecure_key_gen]
initial_wait_time = 1
retry_interval = 3
max_poll_count = 24

[tracing]
service_name = "kms-asc-connector"
endpoint = "http://localhost:4317"

[store]
url = "http://localhost:8088"
