# Set to true to start an emulated KMS backend.
# This option enables a debug mode where a mocked KMS backend is used instead of a real one.
# Useful for testing and development purposes without needing actual KMS services.
debug = false

# configure to match the KMS mode: centralized or threshold
mode = "centralized"

# api url binding
api_url = "0.0.0.0:7077"

# Ethereum Settings
# Configuration settings related to the Ethereum network and smart contract event interactions.
[ethereum]

# chain id
chain_id = 9000

# Listener type, one of FHEVM_V1, FHEVM_V1_1, or COPROCESSOR.
# Specifies the type of listener to be used for processing Ethereum events.
# - FHEVM_V1: Use the FHEVM version 1 listener.
# - FHEVM_V1_1: Use the FHEVM version 1.1 listener.
# - COPROCESSOR: Use the Coprocessor listener.
listener_type = "FHEVM_V1_1"

# URL of the Ethereum WebSocket server.
# Used for establishing a WebSocket connection to an Ethereum node.
wss_url = "ws://localhost:8546"

# Used for establishing an http connection to an Ethereum node.
http_url = "http://localhost:8545"

# Address of the FHE library smart contract on the Ethereum blockchain.
# Used for interactions with the FHE library contract.
fhe_lib_address = "000000000000000000000000000000000000005d"

# Address of the OraclePredeploy or GatewayPredeploy contract on the
# Ethereum blockchain. Used for pre-deployment operations related to the oracle.
oracle_predeploy_address = "c8c9303Cd7F337fab769686B593B87DC3403E0ce"

# Test Address used for testing asynchronous decryption on the Ethereum blockchain.
test_async_decrypt_address = "99F460504563579922352932A42172B3c04a1420"

# Verifying contract address for KMSVerifier EIP712
kmsverifier_vc_address = "66f9664f97F2b50F62D13eA064982f936dE76657"

# Version for KMSVerifier EIP712
kmsverifier_version = "1"

# Name for KMSVerifier EIP712
kmsverifier_name = "KMSVerifier"

# Address of the coprocessor to query for ciphertexts
coprocessor_url = "http://127.0.0.1:8745/"

# optionally explicitly set the gas price
# gas_price = 1_000_000_000

# optionally explicitly set transaction gas limit
gas_limit = 5_000_000

# base gas price, one of current_gas_price or eip1559_max_priority_fee_per_gas
base_gas = "eip1559_max_priority_fee_per_gas"

# gas escalator increase in % of base_gas
gas_escalator_increase = 20

# relayer private key
relayer_key = "7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67"

# KMS Settings
# Configuration settings related to the Key Management System (KMS).
[kms]
# Address of the KMS smart contract on the blockchain.
# Used for interactions with the KMS contract.
contract_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

# Mnemonic phrase for accessing the KMS.
# This is a human-readable string of words used to derive cryptographic keys.
# It should be kept secure and private.
mnemonic = "bachelor similar spirit copper rely carbon web hobby conduct wrap conduct wire shine parrot erosion divert crucial balance lock reason price ignore educate open"

# Base URL of the KMS service.
# Used for making HTTP requests to the KMS service.
address = "http://localhost:9090"

# Key ID used within the KMS.
# Identifies the specific key to be used for cryptographic operations within the KMS.
key_id = "408d8cbaa51dece7f782fe04ba0b1c1d017b1088"

# CRS IDs used within the KMS.
# Identifies the specific CRS' to be used for ZKPs within the KMS.
# The key is the bit parameter used to generate the CRS.
[kms.crs_ids]
# Ths is a list of crs ids with the amount of bits they can handle encryptions for.
# 128 = "00000000000000000000000000000000000000000"
256 = "d8d94eb3a23d22d3eb6b5e7b694e8afcd571d906"

[storage]
url = "http://localhost:8088"

[tracing]
service_name = "gateway"
endpoint = "http://localhost:4317"
