# Set to true to start an emulated KMS backend.  This option enables a debug
# mode where a mocked KMS backend is used instead of a real one.  Useful for
# testing and development purposes without needing actual KMS services.
debug = false

# Configure to match the KMS mode: it must be either centralized or threshold.
mode = "threshold"

# The URL that the gateway API service will listen on.
api_url = "0.0.0.0:7077"

# path to the file that store the state
state_path = "./.GW_STATE"

# The section consists of the configuration settings related to the Ethereum
# network and smart contract event interactions.
[ethereum]

# Ethereum chain ID, used in EIP712 signatures.
chain_id = 12345

# A static salt value, which is used for EIP712 signing in order to distingush
# different dApps.  It is computed as the SHA 256 digest of the string "Zama
# TKMS ASC".  But commented out for now since it needs to be supported in
# fhevmjs see https://github.com/zama-ai/fhevmjs/issues/116
# eip712_salt = "e4edb9fdce7fd5cfd13ebe4ff9931f986b5df5b30ed798e2d72d1ce400b615d9"

# Listener type, one of FHEVM_NATIVE or COPROCESSOR, which specifies the type
# of listener to be used for processing Ethereum events.
# - FHEVM_NATIVE: Use the FHEVM native listener.
# - COPROCESSOR: Use the Coprocessor listener.
listener_type = "COPROCESSOR"

# URL of the Ethereum WebSocket server.  Used for establishing a WebSocket
# connection to an Ethereum node.
wss_url = "ws://localhost:8746"

# URL of the Ethereum http server. Used for establishing an http connection to
# an Ethereum node.
http_url = "http://localhost:8745"

# Address of the FHE library smart ontract on the Ethereum blockchain.  Used
# for interactions with the FHE library contract.
fhe_lib_address = "000000000000000000000000000000000000005d"

# Api key used to retrieve the ciphertext using gRPC call on the Coprocessor.
coprocessor_api_key = "a1503fb6-d79b-4e9e-826d-44cf262f3e05"

# Address of the OraclePredeploy or GatewayPredeploy contract on the Ethereum
# blockchain. Used for pre-deployment operations related to the oracle.
oracle_predeploy_address = "096b4679d45fB675d4e2c1E4565009Cec99A12B1"

# Test Address used for testing asynchronous decryption on the Ethereum
# blockchain.
test_async_decrypt_address = "99F460504563579922352932A42172B3c04a1420"

# Verifying contract address for the KMSVerifier EIP712.
kmsverifier_vc_address = "208De73316E44722e16f6dDFF40881A3e4F86104"

# Version for the KMSVerifier EIP712.
kmsverifier_version = "1"

# Name for the KMSVerifier EIP712.
kmsverifier_name = "KMSVerifier"

# Version for the Reencryption EIP712,
# defined in
# https://github.com/zama-ai/fhevmjs/blob/19fd3b8d63b587f45a3cf1e53c443999d8865de6/src/sdk/keypair.ts#L53-L62
reenc_domain_version = "1"

# Name for the Reencryption EIP712.
reenc_domain_name = "Authorization token"

# Address of the ACL contract.
acl_address = "339EcE85B9E11a3A3AA557582784a15d7F82AAf2"

# Address of the coprocessor to query for ciphertexts (gRPC).
coprocessor_url = "http://127.0.0.1:50055"

# Optionally explicitly set the gas price.
# gas_price = 1_000_000_000

# Optionally explicitly set transaction gas limit.
gas_limit = 5_000_000

# Base gas price, must be one of "current_gas_price" or
# "eip1559_max_priority_fee_per_gas"
base_gas = "eip1559_max_priority_fee_per_gas"

# Gas escalator increase in % of base_gas.
gas_escalator_increase = 20

# Relayer private key.
relayer_key = "7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67"


# Retry config for get_cipertext in the coprocessor mode.
[ethereum.get_ciphertext_retry]

# Set the maximum retry count, resulting in an exponential backoff delay.
max_retries = 6

# The base factor in milliseconds for exponential backoff,
# that can reach up to 32 seconds (1s, 2s, 4s, 8s, 16s, 32s).
factor = 1000

# This section contains the KMS (Key Management System) blockchain settings.
[kms]

# Address of the KMS smart contract on the blockchain.  Used for interactions
# with the KMS contract.
asc_address = "wasm1qwlgtx52gsdu7dtp0cekka5zehdl0uj3fhp9acg325fvgs8jdzksu3v4ff"

# Address of the KMS CSC on the blockchain.
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

# Mnemonic phrase for accessing the KMS.  This is a human-readable string of
# words used to derive cryptographic keys.  Ideally we should storage this in a
# safer location.
mnemonic = "degree fringe genuine soon present soul jelly catch that million van idle ship always silly uphold private mandate great used donate armed shock uphold"

# Base URL of the KMS service.  Used for making HTTP requests to the KMS
# service.
address = "http://localhost:9090"

# Identifies the specific key to be used for cryptographic operations within
# the KMS.
#
# TODO stop-gap these will eventually be fetched from the ASC. This line can be
# removed if the key get setup with the simulator. Should be removed as part of
# https://github.com/zama-ai/fhevm/issues/548
# 
# Key ID used within the KMS.
key_id = "?"
# CRS ID used within the KMS.
crs_id = "?"

# The URL of a key-value storage service used for transferring ciphertexts that
# are too large to be stored on the blockchain between the connector and the
# gateway. The configuration must be the same as what's on the connector.
[storage]
url = "http://localhost:8088"

# Tracing configuration for logging and metrics.
[tracing]

# The service name. This is used to identify the service in the tracing system.
# It is recommended to use the same service name across all instances of the
# service.
service_name = "gateway"

# The endpoint of the tracing system. If it is not set, tracing will be
# redirected to stdout. This is an optional configuration.
endpoint = "http://localhost:4317"
