# Set to true to start an emulated KMS backend.
# This option enables a debug mode where a mocked KMS backend is used instead of a real one.
# Useful for testing and development purposes without needing actual KMS services.
debug = false

# configure to match the KMS mode: centralized or threshold
mode = "centralized"

# api url binding
api_url = "0.0.0.0:7077"

# Ethereum Settings
# Configuration settings related to the Ethereum network and smart contract event interactions.
[ethereum]

# chain id
chain_id = 9000

# Listener type, one of FHEVM_NATIVE or COPROCESSOR.
# Specifies the type of listener to be used for processing Ethereum events.
# - FHEVM_NATIVE: Use the FHEVM native listener.
# - COPROCESSOR: Use the Coprocessor listener.
listener_type = "FHEVM_NATIVE"

# URL of the Ethereum WebSocket server.
# Used for establishing a WebSocket connection to an Ethereum node.
wss_url = "ws://localhost:8546"

# Used for establishing an http connection to an Ethereum node.
http_url = "http://localhost:8545"

# Address of the FHE library smart contract on the Ethereum blockchain.
# Used for interactions with the FHE library contract.
fhe_lib_address = "000000000000000000000000000000000000005d"

# Api key used to retrieve the ciphertext using gRPC call for Coprocessor architecture
coprocessor_api_key = "api-key"

# Address of the OraclePredeploy or GatewayPredeploy contract on the
# Ethereum blockchain. Used for pre-deployment operations related to the oracle.
oracle_predeploy_address = "c8c9303Cd7F337fab769686B593B87DC3403E0ce"

# Test Address used for testing asynchronous decryption on the Ethereum blockchain.
test_async_decrypt_address = "99F460504563579922352932A42172B3c04a1420"

# Verifying contract address for KMSVerifier EIP712
kmsverifier_vc_address = "66f9664f97F2b50F62D13eA064982f936dE76657"

# Version for KMSVerifier EIP712
kmsverifier_version = "1"

# Name for KMSVerifier EIP712
kmsverifier_name = "KMSVerifier"

# Reencryption EIP712 domain info from https://github.com/zama-ai/fhevmjs/blob/19fd3b8d63b587f45a3cf1e53c443999d8865de6/src/sdk/keypair.ts#L53-L62
# Version for Reencryption EIP712
reenc_domain_version = "1"

# Name for Reencryption EIP712
reenc_domain_name = "Authorization token"

# address of the ACL contract
acl_address = "66f9664f97F2b50F62D13eA064982f936dE76657"

# Address of the coprocessor to query for ciphertexts (gRPC)
coprocessor_url = "http://127.0.0.1:50051"

# optionally explicitly set the gas price
# gas_price = 1_000_000_000

# optionally explicitly set transaction gas limit
gas_limit = 5_000_000

# base gas price, one of current_gas_price or eip1559_max_priority_fee_per_gas
base_gas = "eip1559_max_priority_fee_per_gas"

# gas escalator increase in % of base_gas
gas_escalator_increase = 20

# relayer private key
relayer_key = "7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67"

# KMS Settings
# Configuration settings related to the Key Management System (KMS).
[kms]
# Address of the KMS smart contract on the blockchain.
# Used for interactions with the KMS contract.
contract_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

# Mnemonic phrase for accessing the KMS.
# This is a human-readable string of words used to derive cryptographic keys.
# It should be kept secure and private.
mnemonic = "bachelor similar spirit copper rely carbon web hobby conduct wrap conduct wire shine parrot erosion divert crucial balance lock reason price ignore educate open"

# Base URL of the KMS service.
# Used for making HTTP requests to the KMS service.
address = "http://localhost:9090"

# List of prefixed of URL endpoints for the public storage of the KMS.
# The key in the map is the MPC ID of the party. I.e. [1; amount of parties]
[kms.public_storage]
1 = "http://localhost:8088/public-storage/"
2 = "http://localhost:8088/public-storage/"
3 = "http://localhost:8088/public-storage/"
4 = "http://localhost:8088/public-storage/"

[storage]
url = "http://localhost:8088"

[tracing]
service_name = "gateway"
endpoint = "http://localhost:4317"
