# See gateway.toml for the documentation.

debug = false

mode = "centralized"

api_url = "0.0.0.0:7077"

state_path = "./.GW_STATE"

[ethereum]

chain_id = 12345

# eip712_salt = "e4edb9fdce7fd5cfd13ebe4ff9931f986b5df5b30ed798e2d72d1ce400b615d9"

listener_type = "COPROCESSOR"

wss_url = "ws://localhost:8746"

http_url = "http://localhost:8745"

fhe_lib_address = "000000000000000000000000000000000000005d"

coprocessor_api_key = "a1503fb6-d79b-4e9e-826d-44cf262f3e05"

oracle_predeploy_address = "096b4679d45fB675d4e2c1E4565009Cec99A12B1"

test_async_decrypt_address = "99F460504563579922352932A42172B3c04a1420"

kmsverifier_vc_address = "208De73316E44722e16f6dDFF40881A3e4F86104"

kmsverifier_version = "1"

kmsverifier_name = "KMSVerifier"

reenc_domain_version = "1"

reenc_domain_name = "Authorization token"

acl_address = "339EcE85B9E11a3A3AA557582784a15d7F82AAf2"

coprocessor_url = "http://127.0.0.1:50055"

# gas_price = 1_000_000_000

gas_limit = 5_000_000

base_gas = "eip1559_max_priority_fee_per_gas"

gas_escalator_increase = 20

relayer_key = "7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67"

[kms]
asc_address = "wasm1aakfpghcanxtc45gpqlx8j3rq0zcpyf49qmhm9mdjrfx036h4z5se0hfnq"

csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

mnemonic = "bachelor similar spirit copper rely carbon web hobby conduct wrap conduct wire shine parrot erosion divert crucial balance lock reason price ignore educate open"

address = "http://localhost:9090"

key_id = "408d8cbaa51dece7f782fe04ba0b1c1d017b1088"
crs_id = "?"

[storage]
url = "http://localhost:8088"

[tracing]
service_name = "gateway"
endpoint = "http://localhost:4317"
