addresses = ["http://localhost:9090"]
contract = "wasm16jzpxp0e8550c9aht6q9svcux30vtyyyyxv5w2l2djjra46580ws3q80pc"
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"


