# Assuming port forwarding at least one validator node and the kv-store
#
# Change the s3 endpoint below with your path to your s3 content locally
# Follow the readme of simulator https://github.com/zama-ai/kms-core/tree/main/blockchain/simulator
#
s3_endpoint = "/path/to/your/local/aws/folder/aws/threshold"
key_id = ""
object_folder = ["PUB-p1","PUB-p2","PUB-p3","PUB-p4"]
validator_addresses = ["http://localhost:9090"]
http_validator_endpoints = ["http://localhost:36657"]
kv_store_address = "http://localhost:8088"

# TODO: add support for "latest" and automatically get the last contract
# contract-code: 61 this needs to be kept up to date with the k8 cluster
#
asc_address = "wasm1eyfccmjm6732k7wp4p6gdjwhxjwsvje44j0hfx8nkgrm8fs7vqfsuw7sel"

# Address of the CSC
#
csc_address = "wasm1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqr5j2ht"

mnemonic = "museum talent border youth universe accident have kidney daring check hidden carbon valid glance intact object rule creek weather spoil panda brisk swing alone"
faucet_address = "http://localhost:8000"

# Decryption mode used in reencryption reconstruction.
# Options are NoiseFloodSmall and BitDecSmall.
# Must match the deployed core/service setting!
# Only relevant for threshold.
decryption_mode = "NoiseFloodSmall"
