key_id = "408d8cbaa51dece7f782fe04ba0b1c1d017b1088"
crs_id = "d8d94eb3a23d22d3eb6b5e7b694e8afcd571d906"
s3_endpoint = "http://localhost:9000/kms"
key_folder = "PUB"
validator_addresses = ["http://localhost:9090"]
http_validator_endpoints = ["http://localhost:36657"]
kv_store_address = "http://localhost:8088"
contract = "wasm1yyca08xqdgvjz0psg56z67ejh9xms6l436u8y58m82npdqqhmmtqas0cl7"
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"
faucet_address = "http://localhost:8000"

