[package]
name = "asc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
schema = []

[dependencies]
events = { path = "../../events" }
cosmwasm-std = { version = "2.0.2", features = ["staking"] }
sylvia = "1.0.2"
sylvia-derive = "1.0.2"
schemars = "0.8.16"
cosmwasm-schema = "2.0.2"
serde = "1.0.197"
cw-storage-plus = "2.0.0"
hex = "0.4.3"
sha2 = "0.10.8"
bincode = "1.3.3"
anyhow = "1.0.83"
tendermint = "0.36.0"
ibc-clients = "0.52.0"
#ibc-core = "0.52.0"
#ibc-client-cw = "0.52.0"

[dev-dependencies]
cw-multi-test = "2.0.1"
sylvia = { version = "1.0.2", features = ["mt"] }
