[package]
name = "asc"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true

# These libraries are necessary for make this a smart contract within Sylvia :
# https://cosmwasm.github.io/sylvia-book/basics/create-project.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
schema = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std = { workspace = true, features = ["staking"] }
cw-controllers.workspace = true
cw-storage-plus = { workspace = true, features = ["iterator"] }
cw-utils.workspace = true
cw2.workspace = true
events.workspace = true
hex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
sylvia.workspace = true
tfhe-versionable.workspace = true
contracts-common.workspace = true
strum.workspace = true
strum_macros.workspace = true

[dev-dependencies]
aipsc = { path = "../aipsc" }
byteorder = "=1.5.0"
cw-multi-test = "=2.1.1"
ed25519-consensus = "=2.1.0"
rand.workspace = true
sylvia = { workspace = true, features = ["mt"] }
tendermint.workspace = true
tendermint-ipsc = { path = "../tendermint-ipsc", features = ["mock"] }
test-context = "=0.3.0"
csc.workspace = true

[[bin]]
name = "asc-schema"
path = "src/bin/schema.rs"
