[package]
name = "asc"
version = "0.8.0"
edition.workspace = true
publish.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
schema = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std = { workspace = true, features = ["staking"] }
cw-controllers.workspace = true
cw-storage-plus.workspace = true
cw-utils.workspace = true
events = { path = "../../events" , version = "0.8.0" }
hex = "0.4.3"
schemars.workspace = true
serde.workspace = true
sha3 = "0.10.8"
sylvia.workspace = true
sylvia-derive.workspace = true

[dev-dependencies]
aipsc = { path = "../aipsc" }
byteorder = "1.5.0"
cw-multi-test = "=2.1.1"
ed25519-consensus = "2.1.0"
rand.workspace = true
sylvia = { workspace = true, features = ["mt"] }
tendermint.workspace = true
tendermint-ipsc = { path = "../tendermint-ipsc", features = ["mock"] }
test-context = "0.3.0"
