[package]
name = "asc"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
schema = []

[dependencies]
anyhow = "1.0.83"
bincode = "1.3.3"
cosmwasm-schema = "2.0.2"
cosmwasm-std = { version = "2.0.2", features = ["staking"] }
cw-controllers = "2.0.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
events = { path = "../../events" , version = "0.1.0" }
hex = "0.4.3"
ibc-clients = "0.53.0"
schemars = "0.8.16"
serde = "1.0.197"
sha3 = "0.10.8"
sylvia = "1.0.2"
sylvia-derive = "1.0.2"

[dev-dependencies]
cw-multi-test = "2.0.1"
sylvia = { version = "1.0.2", features = ["mt"] }
test-context = "0.3.0"
byteorder = "1.5.0"
