[package]
name = "kms"
version = "0.1.0"
edition = "2021"

[lib] # Central KMS
name = "kms_lib"
path = "src/lib.rs"

[[bin]]
name = "kms-gen"
path = "src/gen.rs"

[[bin]] # Bin to run the gRPC server
name = "kms-server"
path = "src/server.rs"

[[bin]] # Bin to run the gRPC client
name = "kms-client"
path = "src/client.rs"

[dependencies]
aes-prng = "~0.2"
anyhow = "~1.0"
bincode = "~1.3"
crypto_box = {version = "~0.9.1", features = ["salsa20"]}
# Run ssh-add to authenticate your SSH keys to access the private github repo below
distributed-decryption = {git = "ssh://git@github.com/zama-ai/distributed-decryption", rev="880792f" }
ctor = "~0.2"
itertools = "0.12"
k256 = "0.13.3"
nom = "7.1.3"
prost = "0.12.3"
rand = { version = "~0.8", features = ["std", "std_rng"] }
# TODO needed for now to avoid tests timing out
rayon = "1.8.1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "~1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_asn1_der = "0.8.0"
serial_test = "3.0.0"
sha3 = "~0.10.8"
signature = "~2.2"
tfhe = { version = "0.5.1", features = [ "boolean", "shortint", "integer" ]}
tonic = "0.10"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
tracing = { version = "~0.1", features = ["log"] }
tracing-test = "0.2.4"
tracing-subscriber = "0.3.18"
url = "2.5.0"

[target.'cfg(unix)'.dependencies]
tfhe = { version = "0.5.1", features = ["seeder_unix"] }

[dev-dependencies]
ctor = "~0.2"

[build-dependencies]
tonic-build = "0.10"

[features]
slow_tests = []
