[workspace]
resolver = "2"

members = [
    "coordinator",
    "core/threshold",
    "blockchain/protocol",
    "blockchain/proofs",
    "blockchain/smart-contracts/counter-test",
    "blockchain/smart-contracts/configuration",
]
