[package]
name = "distributed-decryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
aes-prng = "0.2.1"
aligned-vec = "~0.5"
anyhow = "~1.0"
async-channel = "~2.1"
async-trait = "~0.1"
async_cell = "~0.2"
backoff = { version = "~0.4", features = ["tokio"] }
bincode = "~1.3"
blake3 = { version = "~1.5", features = ["std"] }
clap = { version = "~4", features = ["derive", "env"] }
concrete-csprng = "~0.4.0"
config = "0.14.0"
const_format = "0.2.32"
crypto_box = { version = "~0.9.1", features = ["salsa20"] }
dashmap = "~5"
derive_more = "~0.99"
enum_dispatch = "0.3.12"
futures = "~0.3"
g2p = "1.0.1"
itertools = "0.12"
k256 = "0.13.1"
lazy_static = "~1.4"
minijinja = { version = "1.0.11", features = ["loader"], optional = true }
mockall = "~0.12.1"
ndarray = { version = "~0.15", features = ["serde"] }
ndarray-stats = "~0.5"
noisy_float = "0.2.0"
nom = "7.1.3"
num-integer = "0.1.45"
num-traits = "0.2"
opentelemetry = "0.21.0"
opentelemetry-otlp = { version = "0.14.0", features = ["tokio"] }
opentelemetry-semantic-conventions = "0.13.0"
opentelemetry-stdout = { version = "0.2.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.21.2", features = ["rt-tokio", "logs"] }
opentelemetry-http = "0.10.0"
prettytable-rs = { version = "~0.10", optional = true }
paste = "1.0.12"
prost = "0.12"
rand = { version = "~0.8" }
rayon = "~1.8"
redis = "0.24.0"
serde = { version = "~1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_asn1_der = "0.8.0"
sha3 = "~0.10.8"
signature = "~2.2"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
tokio = { version = "~1.36", features = ["full", "sync"] }
toml = "~0.8"
tonic = { version = "~0.10", features = ["tls"] }
tonic-health = "~0.10"
tower = { version = "0.4", features = ["retry", "timeout"] }
tower-http = { version = "0.4", features = ["trace"] }
tfhe = { version = "~0.5.1", features = ["boolean", "shortint", "integer"]}
tracing = { version = "~0.1", features = ["log"] }
tracing-opentelemetry = "0.22"
tracing-subscriber = { version = "~0.3.16", features = ["env-filter", "fmt"] }
typed-builder = "0.18.1"
x509-parser = "~0.15"
zeroize = { version = "~1.7", features = ["zeroize_derive"] }
zk-poc = { git = "ssh://git@github.com/zama-ai/zk-poc.git", rev = "169f1e28125e13ae481e7b1012f9afeff0c261b8" }

[build-dependencies]
tonic-build = "~0.10"


[dev-dependencies]
criterion = { version = "~0.5" }
ctor = "~0.2"
proptest = "~1.4"
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }
rstest = "~0.18"
test-log = { version = "0.2", features = ["trace"] }
tracing-test = "0.2"

[[bin]]
name = "flamin"
path = "src/bin/flamingo/flamin.rs"

[[bin]]
name = "flamingo"
path = "src/bin/flamingo/flamingo.rs"

[[bin]]
name = "moby"
path = "src/bin/moby/moby.rs"

[[bin]]
name = "mobygo"
path = "src/bin/moby/mobygo.rs"
required-features = ["choreographer"]

[[bin]]
name = "gen-experiment"
path = "src/bin/benches/gen-experiment.rs"
required-features = ["templating"]


[[bench]]
name = "ddec"
harness = false
required-features = ["testing"]

[[bench]]
name = "decoding"
harness = false

[[bench]]
name = "bench_switch_and_squash"
harness = false

[[bench]]
name = "bench_prss"
harness = false

[[bench]]
name = "prep"
harness = false
required-features = ["testing"]

[[bench]]
name = "bit_dec"
harness = false
required-features = ["testing"]

[[bench]]
name = "ceremony"
harness = false
required-features = ["testing"]

[profile.bench]
debug = true

[features]
testing = []
slow_tests = []
templating = ["minijinja"]
choreographer = ["prettytable-rs"]
