[package]
name = "distributed-decryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-prng = "~0.2"
anyhow = "~1.0"
lazy_static = "~1.4"
nom = "7.1.3"
rand = { version = "~0.8", features = ["std", "std_rng"] }

[dev-dependencies]
rstest = "~0.16"
