[package]
name = "distributed-decryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-prng = "~0.2"
anyhow = "~1.0"
g2p = "1.0.1"
lazy_static = "~1.4"
nom = "7.1.3"
rand = { version = "~0.8", features = ["std", "std_rng"] }
rstest = "~0.16"

[dev-dependencies]
criterion = { version="0.4" }
proptest = "~1.1"
rand_chacha = "~0.3"
rstest = "~0.16"


[[bench]]
name = "decoding"
harness = false
