[package]
name = "kms"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the gRPC server
name = "kms-server"
path = "src/server.rs"

[[bin]] # Bin to run the gRPC client
name = "kms-client"
path = "src/client.rs"

[dependencies]
anyhow = "~1.0"
bincode = "~1.3"
crypto_box = {version = "~0.9.1", features = ["salsa20"]}
ctor = "~0.2"
k256 = "0.13.3"
nom = "7.1.3"
prost = "0.12.3"
rand = { version = "~0.8", features = ["std", "std_rng"] }
rand_chacha = "~0.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "~1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_asn1_der = "0.8.0"
serial_test = "2.0.0"
sha3 = "~0.10.8"
signature = "~2.1"
tfhe = { version = "0.4.1", features = [ "boolean", "shortint", "integer" ] }
tonic = "0.10"
tendermint = "0.34"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "~0.1", features = ["log"] }
tracing-test = "0.2.4"
tracing-subscriber = "0.3.18"

[dev-dependencies]
ctor = "~0.2"

[build-dependencies]
tonic-build = "0.10"