[package]
name = "distributed-decryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
aes-prng = "~0.2"
anyhow = "~1.0"
async-channel = "~1.8"
async-trait = "~0.1"
async_cell = "~0.2"
backoff = { version = "~0.4", features = ["tokio"] }
bincode = "~1.3"
byteorder = "~1.4"
blake3 = { version = "~1.3", features = ["std"] }
clap = { version = "~4", features = ["derive", "env"] }
concurrent-queue = "2.1.0"
dashmap = "~5"
derive_more = "~0.99"
futures = "~0.3"
g2p = "1.0.1"
itertools = "0.10"
lazy_static = "~1.4"
ndarray = { version = "~0.15", features = ["serde"] }
ndarray-stats = "~0.5"
noisy_float = "0.2.0"
nom = "7.1.3"
num-integer = "0.1.45"
prost = "0.11"
paste = "1.0.12"
rand = { version = "~0.8", features = ["std", "std_rng"] }
rand_chacha = "~0.3"
regex = { version = "1", features = ["unicode-case"] }
serde = { version = "~1.0", features = ["derive", "rc"] }
serde_json = "1.0"
static_assertions = "~1.1"
tfhe = { git = "https://github.com/zama-ai/tfhe-rs.git", features = ["boolean", "shortint", "integer"] }
tokio = { version = "~1.28", features = ["full", "sync"] }
toml = "~0.7"
tracing = { version = "~0.1", features = ["log"] }
tracing-subscriber = { version = "~0.3.16", features = ["env-filter"] }
tracing-test = "0.2"
tonic = { version = "~0.9", features = ["tls"] }
x509-parser = "~0.15"

[build-dependencies]
tonic-build = "~0.9"


[dev-dependencies]
criterion = { version="0.5" }
proptest = "~1.2"
rand_chacha = "~0.3"
rstest = "~0.17"


[[bin]]
name = "flamin"
path = "src/bin/flamingo/flamin.rs"

[[bin]]
name = "flamingo"
path = "src/bin/flamingo/flamingo.rs"

[[bin]]
name = "moby"
path = "src/bin/moby/moby.rs"

[[bin]]
name = "mobygo"
path = "src/bin/moby/mobygo.rs"


[[bench]]
name = "decoding"
harness = false

[[bench]]
name = "prss"
harness = false
