[workspace]
resolver = "2"

members = [
    "coordinator",
    "core/threshold",
    "blockchain/client",
    "blockchain/connector",
    "blockchain/cosmos-proto",
    "blockchain/events",
    "blockchain/proofs",
    "blockchain/contracts/asc",
]
