[package]
name = "distributed-decryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
aes-prng = "~0.2"
aligned-vec = "~0.5"
anyhow = "~1.0"
async-channel = "~1.9"
async-trait = "~0.1"
async_cell = "~0.2"
backoff = { version = "~0.4", features = ["tokio"] }
bincode = "~1.3"
byteorder = "~1.5"
blake3 = { version = "~1.5", features = ["std"] }
clap = { version = "~4", features = ["derive", "env"] }
concurrent-queue = "2.1.0"
crypto_box = {version = "~0.9.1", features = ["salsa20"]}
dashmap = "~5"
derive_more = "~0.99"
digest = "0.10.7"
futures = "~0.3"
g2p = "1.0.1"
itertools = "0.11"
k256 = "0.13.1"
lazy_static = "~1.4"
mockall = "~0.11"
ndarray = { version = "~0.15", features = ["serde"] }
ndarray-stats = "~0.5"
noisy_float = "0.2.0"
nom = "7.1.3"
num-integer = "0.1.45"
num-traits = "0.2"
prost = "0.12"
paste = "1.0.12"
rand = { version = "~0.8", features = ["std", "std_rng"] }
rand_chacha = "~0.3"
regex = { version = "1", features = ["unicode-case"] }
serde = { version = "~1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_asn1_der = "0.8.0"
sha3 = "~0.10.8"
signature = "~2.1"
static_assertions = "~1.1"
# TODO this should be updated at some point so we don't use a specific weird branch
# Ensure that "# ~/.gitconfig \n [credential] \n helper = store" is added to .gitconfig
tfhe = { git = "ssh://git@github.com/zama-ai/tfhe-rs-internal.git", branch = "noise_gap_exp", features = [
    "boolean",
    "shortint",
    "integer",
] }
tokio = { version = "~1.33", features = ["full", "sync"] }
toml = "~0.8"
tracing = { version = "~0.1", features = ["log"] }
tracing-subscriber = { version = "~0.3.16", features = ["env-filter", "fmt"] }
tonic = { version = "~0.10", features = ["tls"] }
x509-parser = "~0.15"

[build-dependencies]
tonic-build = "~0.10"


[dev-dependencies]
criterion = { version = "~0.5"}
ctor = "~0.2"
env_logger = "0.10"
proptest = "~1.3"
rand_chacha = "~0.3"
rstest = "~0.18"
test-log = { version = "0.2", features = ["trace"] }
tracing-test = "0.2"
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }


[[bin]]
name = "flamin"
path = "src/bin/flamingo/flamin.rs"

[[bin]]
name = "flamingo"
path = "src/bin/flamingo/flamingo.rs"

[[bin]]
name = "moby"
path = "src/bin/moby/moby.rs"

[[bin]]
name = "mobygo"
path = "src/bin/moby/mobygo.rs"

[[bench]]
name = "decoding"
harness = false

[[bench]]
name = "bench_prss"
harness = false

[[bench]]
name = "prep"
harness = false

[[bench]]
name = "bit_dec"
harness = false

[profile.bench]
debug = true

[features]
extensive_testing = []
