version: "3"

services:
  kms_endpoint:
    build: .
    ports:
      - "50051:50051"

  full_node:
    image: ghcr.io/zama-ai/ethermint-dev-node:v0.2.4
    ports:
      - "26656:26656"
      - "26657:26657"
      - "8545:8545"
    volumes:
      - ./scripts/run_developer_image.sh:/start.sh
    entrypoint: ["/bin/bash", "/start.sh"]

  light_node:
    image: cometbft/cometbft:v0.38.5
    depends_on:
      - full_node
    ports:
      - "8888:8888"
    entrypoint: "/bin/bash"
    command: >
      -c "sleep 20;
      curl -s http://full_node:26657/commit | jq -r '.result.signed_header.commit.block_id.hash';
      cometbft light ethermint_9000-1 -p http://full_node:26657 -w http://full_node:26657 --hash $(curl -s http://full_node:26657/commit | jq -r '.result.signed_header.commit.block_id.hash') --height $(curl -s http://full_node:26657/commit | jq -r '.result.signed_header.header.height') --laddr tcp://0.0.0.0:8888 --sequential";
