services:
  # Docker-file in https://github.com/zama-ai/kms-core-infra/blob/main/docker/faucet/Dockerfile
  # this means that the CI does not have access to it by default
  # The easiest option is to split the faucet to another file
  dev-kms-blockchain-faucet:
    image: ghcr.io/zama-ai/cosmos-faucet:0.32.4
    ports:
      - "8000:8000"
    entrypoint: /usr/local/bin/cosmos-faucet start http://dev-kms-blockchain-validator:26657
    # Figure out why this doesn't work
    environment:
      # TODO: set FAUCET_MMENMONIC into .env file
      # TODO: store .env file backup in secret manager
      # TODO: find a better way to handle this mnemonic which is the result of
      # `wasmd keys add faucet-testing` in the validator
      - FAUCET_MNEMONIC=wise answer bring salad ghost excess reform canoe silent distance pulp apart struggle rebel cotton traffic tube cable ability become teach base spoil easy
      - FAUCET_TOKENS=ucosm
      - FAUCET_CREDIT_AMOUNT_TKN=1000000000000
      - FAUCET_ADDRESS_PREFIX=wasm
      - FAUCET_PORT=8000
      - FAUCET_COOLDOWN_TIME=0
    depends_on:
      dev-kms-blockchain-validator:
        condition: service_healthy
