name: zama-kms-centralized
services:
  dev-kms-core-status:
    image: alpine
    depends_on:
      dev-kms-core:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 1 && exit 0
      "

  # KMS-Core-centralized
  # TODO: move the upload of the pub-key from the validator to the core -> or maybe the connector?
  # anyway where the keys really are
  dev-kms-core:
    build:
      context: .
      dockerfile: core/service/operations/docker/dev.dockerfile
    image: kms-core:latest
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc-health-probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    volumes:
      - minio_secrets:/minio_secrets
    depends_on:
      dev-s3-mock-setup:
        condition: service_completed_successfully
    entrypoint: >
      /bin/sh -c "
      chmod +x /app/scripts/pub_key_to_minio.sh &&
      /app/scripts/pub_key_to_minio.sh &&
      kms-server centralized
      "

  dev-kms-connector:
    build:
      context: .
      dockerfile: blockchain/connector/operations/docker/dev.dockerfile
    image: kms-connector:latest
    command:
      - "kms-blockchain-connector"
    environment:
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://dev-kms-blockchain-validator:9090
      - ASC_CONN__CORE__ADDRESSES=http://dev-kms-core:50051
      - ASC_CONN__STORE__URL=http://dev-kv-store:8088
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__RETRY_INTERVAL=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__RETRY_INTERVAL=1
    depends_on:
      dev-kms-blockchain-validator:
        condition: service_healthy
      dev-kms-core:
        condition: service_healthy
