name: zama-kms-base

# A docker compose file to be able to debug the kms
# The images take a bit of time to build

# TODO: handle networking stuff
# TODO: figure out if we need the gateway here, if so, do we have a way to mimic the FHEVM?
# TODO: create a overload version of this docker compose to use only ghcr main images
# TODO: create a overload version of this docker compose to use only ghcr released images
# TODO: add a faucet
# TODO: add minio to simulate s3 + some config file for the endpoint

services:
  # KMS-Blockchain validator node
  dev-kms-blockchain-validator:
    image: ghcr.io/zama-ai/kms-blockchain-asc-dev:${DOCKER_IMAGES_TAG}

  # KV-Store
  # TODO: add healthcheck
  dev-kv-store:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:${DOCKER_IMAGES_TAG}

  # S3 mock
  dev-s3-mock:
    image: quay.io/minio/minio

  # Minio client to create access keys
  dev-s3-mock-setup:
    image: quay.io/minio/mc

