name: zama-kms-centralized
services:
  # Deploy smart contracts
  dev-kms-blockchain-asc-deploy:
    environment:
      - MODE=centralized

  # KMS-Core-centralized
  # TODO: move the upload of the pub-key from the validator to the core -> or maybe the connector?
  # anyway where the keys really are
  dev-kms-core:
    image: ghcr.io/zama-ai/kms-service:latest
    environment:
      - DOCKER_BUILDKIT=1
      - RUST_LOG=info,tonic=info,h2=info
    build:
      context: .
      dockerfile: core/service/operations/docker/ci.dockerfile
      args:
        LTO_RELEASE: release-lto-off
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc-health-probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    volumes:
      - minio_secrets:/minio_secrets
      - ./core/service/config/:/app/kms/core/service/config
    entrypoint: >
      /bin/sh -c "
      export AWS_ACCESS_KEY_ID=$$(cat /minio_secrets/access_key) &&
      export AWS_SECRET_ACCESS_KEY=$$(cat /minio_secrets/secret_key) &&
      echo 'Generating signing keys' &&
      kms-gen-keys --pub-url s3://kms --aws-s3-endpoint http://dev-s3-mock:9000 --aws-region us-east-1 --priv-url file://./keys --cmd signing-keys centralized &&
      echo 'Starting kms service' &&
      kms-server --config-file config/compose_centralized.toml
      "
    depends_on:
      dev-s3-mock-setup:
        condition: service_completed_successfully

  dev-kms-connector:
    build:
      context: .
      dockerfile: blockchain/connector/operations/docker/ci.dockerfile
      args:
        LTO_RELEASE: release-lto-off
    image: ghcr.io/zama-ai/kms-blockchain-connector:latest
    volumes:
      - ./blockchain/connector/config/:/app/kms-connector/config
    command:
      - "kms-blockchain-connector"
      - "--config-file"
      - "config/default.toml"
    environment:
      - DOCKER_BUILDKIT=1
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://dev-kms-blockchain-validator:9090
      - ASC_CONN__CORE__ADDRESSES=http://dev-kms-core:50051
      - ASC_CONN__STORE__URL=http://dev-kv-store:8088
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__RETRY_INTERVAL=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__RETRY_INTERVAL=1
    depends_on:
      dev-kms-blockchain-validator:
        condition: service_healthy
      dev-kms-core:
        condition: service_healthy
      dev-kms-blockchain-asc-deploy:
        condition: service_healthy