env_files = [ { path = ".env.makefile", defaults_only = true } ]

[tasks.docker-image]
command = "docker"
args = ["build", "--ssh", "default", "-t", "ddec", "."]

[tasks.build-bench-grpc]
command = "cargo"
args = ["run", "--bin", "docker-benches", "--features", "docker-compose-benches", "--", "-n", "${NUM_PARTIES}", "-t", "${THRESHOLD}", "-f", "${OUTPUT_DOCKER_COMPOSE_FILE}"]

[tasks.start-parties]
command = "docker-compose"
args = ["--progress=quiet", "-f", "${OUTPUT_DOCKER_COMPOSE_FILE}", "up", "--wait", "--quiet-pull"]
dependencies = ["build-bench-grpc"]

[tasks.stop-parties]
script = '''
docker compose -f ${OUTPUT_DOCKER_COMPOSE_FILE} logs > ${OUTPUT_DOCKER_COMPOSE_LOG_FILE}
docker compose --progress=quiet -f ${OUTPUT_DOCKER_COMPOSE_FILE} down
'''

[tasks.experiment-name]
script = '''
echo ""
echo ""
echo "========================================================="
echo "=                                                       ="
echo "= Experiment: ${EXPERIMENT_NAME}                        "
echo "=                                                       "
echo "= Parties: ${NUM_PARTIES}                               "
echo "= Threshold: ${THRESHOLD}                               "
echo "= Messages: ${NUM_MESSAGES}                             "
echo "= Protocol: ${PROTOCOL}                                 "
echo "=                                                       ="
echo "========================================================="
echo ""
echo ""
'''

[tasks.choreo-init]
env = { "RUST_LOG" = "info", RUST_BACKTRACE = "1"}
command = "cargo"
args = ["run", "--bin", "mobygo", "--features", "choreographer", "--", "-n", "${NUM_PARTIES}", "init", "-t", "${THRESHOLD}", "--lwe-params-file", "${LWE_PARAMS_FILE_PATH}"]

[tasks.choreo-decrypt]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = ["run", "--bin", "mobygo","--features", "choreographer", "--", "-n", "${NUM_PARTIES}", "--number-messages", "${NUM_MESSAGES}", "--session-store","${SESSION_STORE}", "decrypt", "-t", "${THRESHOLD}", "-p", "${PROTOCOL}"]

[tasks.choreo-results]
env = { "RUST_LOG" = "mobygo=info"}
command = "cargo"
args = ["run", "--bin", "mobygo","--features", "choreographer", "--", "-n", "${NUM_PARTIES}", "--session-store", "${SESSION_STORE}", "results"]

[tasks.sleep]
command = "sleep"
args = ["2"]

[tasks.grpc-bench]
run_task = { name = ["experiment-name", "start-parties", "choreo-init", "choreo-decrypt", "choreo-results"], fork = true, cleanup_task = "stop-parties" }


[tasks.docker-image-ci]
command = "docker"
args = ["build", "--build-arg=CONCRETE_ACTIONS_TOKEN=${CONCRETE_ACTIONS_TOKEN}", "-f", "operations/docker/Dockerfile.ci", "-t", "ddec", "."]

[tasks.ci-test]
run_task = { name = ["docker-image-ci", "grpc-bench-4-1-1-prss"] }

[tasks.grpc-bench-4-1-1-prss]
env_files = [ { path = "experiments/bench-p4_t1_msg1_prss.env" } ]
run_task = { name = ["grpc-bench"] }
description = "4 parties, 1 threshold, 1 messages, PRSS"


[tasks.grpc-bench-4-1-10-prss]
env_files = [ { path = "experiments/bench-p4_t1_msg10_prss.env" } ]
run_task = { name = ["grpc-bench"] }
description = "4 parties, 1 threshold, 10 messages, PRSS"

[tasks.grpc-bench-4-1-30-prss]
env_files = [ { path = "experiments/bench-p4_t1_msg30_prss.env" } ]
run_task = { name = ["grpc-bench"] }
description = "4 parties, 1 threshold, 30 messages, PRSS"

[tasks.grpc-bench-10-2-20-prss]
env_files = [ { path = "experiments/bench-p10_t2_msg20_prss.env" } ]
run_task = { name = ["grpc-bench"] }
description = "10 parties, 2 threshold, 20 messages, PRSS"

[tasks.grpc-bench-16-5-40-prss]
env_files = [ { path = "experiments/bench-p16_t5_msg40_prss.env" } ]
run_task = { name = ["grpc-bench"] }
description = "16 parties, 5 threshold, 40 messages, PRSS"

[tasks.grpc-bench-5-1-10-large]
env_files = [ { path = "experiments/bench-p5_t1_msg10_large.env" } ]
run_task = { name = ["grpc-bench"] }
description = "5 parties, 1 threshold, 10 messages, LargeDecryption"

[tasks.grpc-bench-10-2-20-large]
env_files = [ { path = "experiments/bench-p10_t2_msg20_large.env" } ]
run_task = { name = ["grpc-bench"] }
description = "10 parties, 2 threshold, 20 messages, LargeDecryption"

[tasks.grpc-bench-100-10-40-large]
env_files = [ { path = "experiments/bench-p100_t10_msg40_large.env" } ]
run_task = { name = ["grpc-bench"] }
description = "100 parties, 10 threshold, 40 messages, LargeDecryption"

[tasks.run-grpc-benchmarks]
run_task = { name = ["docker-image", "grpc-bench-4-1-10-prss", "grpc-bench-10-2-20-prss", "grpc-bench-16-5-40-prss", "grpc-bench-5-1-10-large", "grpc-bench-10-2-20-large", "grpc-bench-100-10-40-large"] }
