tick_interval_secs = 3
storage_path = "./temp/events.toml"

[oracle]
addresses = ["http://localhost:26657"]

[blockchain]
addresses = ["http://localhost:9090"]
contract = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

[blockchain.signkey]
# It should be either mnemonic or bip32
mnemonic = "feel wife neither never floor volume express actor initial year throw hawk pink gaze deny prevent helmet clump hurt hour river behind employ ribbon"
bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
denom = "ucosm"
amount = 100000

[coordinator]
shares_needed = 2
addresses = ["http://localhost:8080"]

[coordinator.timeout_config]
channel_timeout = 60

[coordinator.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[coordinator.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[coordinator.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[coordinator.timeout_config.decryption]
initial_wait_time = 10
retry_interval = 5
max_poll_count = 24

[coordinator.timeout_config.reencryption]
initial_wait_time = 10
retry_interval = 5
max_poll_count = 24

[tracing]
service_name = "kms-asc-connector"
endpoint = "http://localhost:4317"

