tick_interval_secs = 3
storage_path = "./temp/events.toml"
mode = "request"

[blockchain]
addresses = ["http://localhost:9090"]
contract = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

[blockchain.signkey]
# It should be either mnemonic or bip32
mnemonic = "feel wife neither never floor volume express actor initial year throw hawk pink gaze deny prevent helmet clump hurt hour river behind employ ribbon"
bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
denom = "ucosm"
amount = 100000

[coordinator]
parties = 3
addresses = ["http://localhost:8080"]
shares_needed = 2

[tracing]
service_name = "kms-asc-connector"
endpoint = "http://localhost:4317"

