grpc_addresses = ["htpp://localhost:9090"]
contract_addresses = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
tick_interval_secs = 3
storage_path = "./temp/events.toml"

[tracing]
service_name = "kms-asc-connector"
endpoint = "http://localhost:4317"

