# The interval in number of seconds that the subscriber waits before every
# attempt to query the KMS blockchain to handle new events.
tick_interval_secs = 1

# This section describes information for the KMS blockchain client so that it
# can make transactions to the KMS blockchain.
[blockchain]

# This is the grpc address for that the blockchain client connects to for
# sending transactions to CosmWasm (KMS blockchain).
addresses = ["http://localhost:9090"]

# The Application Smart Contract address. See
# kms-core/blockchain/contracts/asc/README.md for more documentation.
asc_address = "wasm1aakfpghcanxtc45gpqlx8j3rq0zcpyf49qmhm9mdjrfx036h4z5se0hfnq"

# The Configuration Smart Contract address. See
# kms-core/blockchain/contracts/csc/README.md for more documentation.
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

# This section holds the private signing key for sending transactions on the
# KMS blockchain. Ideally we want to keep the signing key in a safer location,
# instead of in the plain.  Two formats are supported, mnemonic and bip32, one
# of the must be set.  If both are set then the mnemonic is used.
[blockchain.signkey]

# The signing in the mnemonic format.
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"
# The signing in the bip32 format.
# bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

# This sections holds information on the blockchain transaction fees.
[blockchain.fee]

# The denomination of the gas limit, defaults to "ucosm" if unset.
denom = "ucosm"

# The gas limit.
amount = 3000000

# Optional sharding configuration.
[sharding]

# The index specifies the index of the current connector, which must be lower
# than the total value. If there is more than one connector in use for one
# logical party, their indices must be unique.
index = 0

# The total number of shards.
total = 1

# This section specifies how the connector communicates with KMS core. The
# connector can send requests and receive responses. The responses are
# asynchronous so majority of the configuration in this section is dedicated to
# configuring how the connector should poll for responses.
[core]

# The URL of the KMS core.
addresses = ["http://localhost:50051"]

# The GRPC timeout for communicating with KMS core.
[core.timeout_config]
channel_timeout = 60

# Polling configuration for a CRS response.
[core.timeout_config.crs]

# How long to wait to begin polling in seconds.
initial_wait_time = 10

# How many seconds to wait between every polling attempt.
retry_interval = 10

# How many times to poll.
max_poll_count = 200

# Polling configuration for an insecure CRS response.
[core.timeout_config.insecure_crs]
initial_wait_time = 9
retry_interval = 3
max_poll_count = 36

# Polling configuration for a KeyGen response.
[core.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 150

# Polling configuration for an insecure KeyGen response.
[core.timeout_config.insecure_key_gen]
initial_wait_time = 9
retry_interval = 3
max_poll_count = 60

# Polling configuration for a Preproc response.
[core.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 150

# Polling configuration for a Decryption response.  Be aware that decryption
# delay can vary greatly depending on the message size.
[core.timeout_config.decryption]
initial_wait_time = 0
retry_interval = 3
max_poll_count = 100

# Polling configuration for a Reencryption response.  Be aware that
# reencryption delay can vary greatly depending on the message size.
[core.timeout_config.reencryption]
initial_wait_time = 0
retry_interval = 3
max_poll_count = 100

# Polling configuration for a VerifyProvenCt response.
[core.timeout_config.verify_proven_ct]
initial_wait_time = 1
retry_interval = 1
max_poll_count = 24

# Tracing configuration for logging and metrics.
[tracing]

# The service name. This is used to identify the service in the tracing system.
# It is recommended to use the same service name across all instances of the
# service.
service_name = "kms-asc-connector"

# The endpoint of the tracing system. If it is not set, tracing will be
# redirected to stdout. This is an optional configuration.
endpoint = "http://localhost:4317"

# The URL of a key-value storage service used for transferring ciphertexts that
# are too large to be stored on the blockchain between the connector and the
# gateway. The configuration must be the same as what's on the gateway.
[store]
url = "http://localhost:8088"
