tick_interval_secs = 3
storage_path = "./temp/events.toml"

[blockchain]
grpc_addresses = ["htpp://localhost:9090"]
contract_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
# It should be either mnemonic or bip32_private_key
mnemonic_wallet = "pistol kiwi cousin ..."
bip32_private_key = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
coin_denom = "ucosm"
amount = 100000

[coordinator]
n_parties = 3
addresses = ["http://localhost:8080"]

[tracing]
service_name = "kms-asc-connector"
endpoint = "http://localhost:4317"

