[package]
name = "kms-core-common"
version = "0.9.0-rc11"
edition.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.203", features = ["derive", "rc"] }
tfhe-versionable = { version = "0.3.1" }
kms-core-backward-compatibility = { path = "../backward-compatibility", version = "0.9.0-rc3" , features = ["load", "tests"], optional = true }

[features]
testing = ["dep:kms-core-backward-compatibility"]
