[package]
name = "kms-core-common"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.203", features = ["derive", "rc"] }
tfhe = { git = "https://github.com/zama-ai/tfhe-rs.git", rev = "f3b89e83d741cf89a8277a98eb0f2665987ee456", features = [
    "boolean",
    "shortint",
    "integer",
] } # == tfhe-rs v0.6.3
