[package]
name = "contracts-common"
version.workspace = true
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cosmwasm-std.workspace = true
tfhe-versionable.workspace = true
serde = { workspace = true, features = ["derive"] }
events.workspace = true
sylvia.workspace = true
strum.workspace = true
cw2.workspace = true
cw-storage-plus.workspace = true
cosmwasm-schema.workspace = true

[dev-dependencies]
contracts-common = { workspace = true, features = ["testing"] }
cw-multi-test = "=2.1.1"
cw2.workspace = true
sylvia = { workspace = true, features = ["mt"] }
schemars.workspace = true

[features]
testing = []