[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.59"
cosmrs = { version = "0.16.0", features = ["rpc", "dev", "cosmwasm", "bip32"] }
serde = "1.0.198"
serde_json = "1.0.116"
tokio = "~1.36"
deep_space = "2.24.1"
cosmos-sdk-proto = "0.21.1"
sha2 = "0.10.8"
hmac = "0.12.1"
secp256k1 = "0.29.0"
rand = "0.8.5"
hex = "0.4.3"
