[service]
listen_address = "0.0.0.0"
listen_port = 50051
timeout_secs = 360
# maximum grpc message size in bytes
grpc_max_message_size = 20971520 # 20 MiB

[tracing]
service_name = "kms-centralized"
endpoint = "http://localhost:4317"

[aws]
region = "us-east-1"
s3_endpoint = "http://dev-s3-mock:9000"

[public_vault]
storage = "s3://kms"

[private_vault]
storage = "file://./keys"
