# See default_1.toml for the documentation.

[service]
listen_address = "0.0.0.0"
listen_port = 50051
timeout_secs = 360
grpc_max_message_size = 20971520 # 20 MiB

[tracing]
service_name = "kms-centralized"
endpoint = "http://localhost:4317"

[aws]
region = "us-east-1"
s3_endpoint = "http://dev-s3-mock:9000"

[public_vault]
storage = "s3://kms"
storage_cache_size = 1000

[private_vault]
storage = "file://./keys"

[rate_limiter_conf]
bucket_size = 50000
dec = 1
reenc = 1
crsgen = 100
preproc = 5000
keygen = 1000
verify_proven_ct = 1