[service]
listen_address = "0.0.0.0"
listen_port = 50051
timeout_secs = 360
# maximum grpc message size in bytes
grpc_max_message_size = 20971520 # 20 MiB

[tracing]
service_name = "kms-centralized"
endpoint = "http://localhost:4317"

# The two sections below are optional. Two URL schemas are supported: file://
# and s3://. The paths can be the same for the different storage types and for
# different parties.

[public_vault]
storage = "file://./keys"

[private_vault]
storage = "file://./keys"
