# See default_1.toml for the documentation.

[service]
listen_address = "0.0.0.0"
listen_port = 50400
timeout_secs = 360
grpc_max_message_size = 20971520 # 20 MiB
decryption_mode = "NoiseFloodSmall"

[tracing]
service_name = "kms-threshold-4"
endpoint = "http://localhost:4317"

[aws]
region = "us-east-1"
s3_endpoint = "http://dev-s3-mock:9000"

[public_vault]
storage = "file://./keys"

[private_vault]
storage = "file://./keys"

[threshold]
listen_address = "0.0.0.0"
listen_port = 50004

my_id = 4

threshold = 1
dec_capacity = 10000
min_dec_cache = 6000
num_sessions_preproc = 2

tls_cert_path = "certs/cert_p4.pem"
tls_key_path = "certs/key_p4.pem"

decryption_mode = "NoiseFloodSmall"

[[threshold.peers]]
party_id = 1
address = "p1"
port = 50001
tls_cert_path = "certs/cert_p1.pem"

[[threshold.peers]]
party_id = 2
address = "p2"
port = 50002
tls_cert_path = "certs/cert_p2.pem"

[[threshold.peers]]
party_id = 3
address = "p3"
port = 50003
tls_cert_path = "certs/cert_p3.pem"

[[threshold.peers]]
party_id = 4
address = "p4"
port = 50004
tls_cert_path = "certs/cert_p4.pem"

[threshold.core_to_core_net]
message_limit = 70
multiplier = 1.1
max_interval = 5
max_elapsed_time = 300
network_timeout = 10
network_timeout_bk = 300
network_timeout_bk_sns = 1200
max_en_decode_message_size = 2147483648

# [threshold.preproc_redis]
# host = "redis://127.0.0.1"


[telemetry]
tracing_service_name = "kms-threshold-4"
# tracing_endpoint = "http://localhost:4317"
metrics_bind_address = "0.0.0.0:9646"

[telemetry.batch]
max_queue_size = 8192
max_export_batch_size = 2048
max_concurrent_exports = 4
scheduled_delay_ms = 500
export_timeout_ms = 5000

[rate_limiter_conf]
bucket_size = 50000
dec = 1
reenc = 1
crsgen = 100
preproc = 5000
keygen = 1000
verify_proven_ct = 1
