# See default_1.toml for the documentation.

[service]
listen_address = "0.0.0.0"
listen_port = 50051
timeout_secs = 360
grpc_max_message_size = 20971520 # 20 MiB

[tracing]
service_name = "kms-centralized"
endpoint = "http://localhost:4317"

[aws]
region = "eu-west-3"
imds_endpoint = "http://localhost:5000"
s3_endpoint = "https://localhost:6000"
awskms_endpoint = "https://localhost:7000"

[public_vault]
storage = "s3://zama_kms_public_keys"
storage_cache_size = 1000

[private_vault]
storage = "s3://zama_kms_private_keys"
storage_cache_size = 1000
keychain = "awskms://zama_kms_storage_root_key"
