[package]
name = "events"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "~1.0"
async-trait = {version = "~0.1", optional = true}
cosmwasm-std = { version = "2.0.2" }
cosmwasm-schema = "2.0.2"
cosmos-proto = { path = "../cosmos-proto", optional = true }
hex = "0.4.3"
koit-toml = { version = "=0.2.1", optional = true }
opentelemetry = { version = "0.22", features = ["metrics" ], optional = true }
opentelemetry_sdk = { version = "0.22", features = ["metrics", "rt-tokio"], optional = true }
retrying = { version = "0.1.0", features = ["tokio"], optional = true }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
thiserror = { version = "1.0.58", optional = true }
tokio = { version = "1.37", features = ["full"], optional = true }
tonic = { version = "0.11", features = ["transport","tls","tls-roots"], optional = true }
tracing = { version = "~0.1", features = ["log"] }
typed-builder = "0.18.1"

[build-dependencies]
tonic-build = "~0.10"

[dev-dependencies]
mockall = "0.12.1"
quickcheck = "1.0.3"
quickcheck_macros = "1"
test-context = "0.3.0"
tracing-subscriber = { version = "~0.3.16", features = ["env-filter", "fmt"] }

[features]
default = []
subscription = [
    "dep:async-trait",
    "dep:cosmos-proto",
    "dep:koit-toml",
    "dep:opentelemetry",
    "dep:opentelemetry_sdk",
    "dep:retrying",
    "dep:thiserror",
    "dep:tokio",
    "dep:tonic",
]




