[package]
name = "events"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { version = "2.0.1" }
serde = { version = "1.0.197", features = ["derive"] }
strum = "0.26"
strum_macros = "0.26"
typed-builder = "0.18.1"

