[package]
name = "kms-blockchain-connector"
version = "0.7.1"
edition.workspace = true
publish.workspace = true
authors.workspace = true


[dependencies]
anyhow = "~1.0"
async-trait = "~0.1"
bincode = "1.3.3"
clap = { version = "~4", features = ["derive", "env"] }
kms = { path = "../../core/service", default-features = false, features = ["grpc-client"] , version = "0.7.1" }
config = "0.14.0"
dashmap = "6"
enum_dispatch = "0.3.12"
events = { path = "../events", features = ["subscription"] , version = "0.7.1" }
kms-blockchain-client = { path = "../client" , version = "0.7.1" }
lazy_static = "1.5"
opentelemetry = { version = "0.23", features = ["metrics"] }
opentelemetry-otlp = { version = "0.16.0", features = ["tokio"] }
opentelemetry-prometheus = "0.16.0"
opentelemetry-semantic-conventions = { version = "0.15.0" }
opentelemetry-stdout = { version = "0.4.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.23", features = ["rt-tokio", "logs", "metrics"] }
prometheus = "=0.13.4"
retrying = { version = "0.1.0", features = ["tokio"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
tokio = { version = "1.37", features = ["full"] }
tonic = { version = "0.11", features = ["transport","tls","tls-roots"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-opentelemetry = "0.24"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
typed-builder = "0.18.1"
hex = "0.4.3"
reqwest = "0.12.4"
sha2 = "0.10.8"
byteorder = "1.5.0"

[dev-dependencies]
kms = { path = "../../core/service", features = ["testing"] , version = "0.7.1" }
alloy-sol-types = "0.7.6"
alloy-primitives = "0.7.6"
serial_test = "3.1.1"
temp-env = "0.3"
test-context = "0.3.0"
test-utilities = { path = "./utilities" }
tracing-test = "0.2.4"
rand = "0.8.5"

[features]
slow_tests = []
