[package]
name = "connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "~0.1"
cosmwasm-std = { version = "2.0.1" }
events = { path = "../events", features = ["subscription"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36", features = ["full"] }
tracing = { version = "~0.1", features = ["log"] }
tracing-subscriber = { version = "~0.3.16", features = ["env-filter", "fmt"] }

