# Configuration for KMS Connector Instance 4

service_name = "kms-connector-4"

# BIP39 mnemonic phrase for wallet generation (required)
mnemonic = "test test test test test test test test test test test junk"

# Chain ID for the L2 network (required)
chain_id = 654321

# Address of the DecryptionManager contract (required)
decryption_manager_address = "0x0000000000000000000000000000000000000000"

# Address of the HTTPZ contract (required)
httpz_address = "0x0000000000000000000000000000000000000001"

# KMS-core gRPC endpoint (required)
kms_core_endpoint = "http://localhost:50055"

# GateWay L2 WebSocket RPC URL endpoint (required)
gwl2_url = "ws://localhost:8757"

# Size of the event processing channel (optional)
channel_size = 1000
