url = "http://127.0.0.1:50051"

# The two settings below are optional and are only used for file storage
public_storage_path = "keys"
private_storage_path = "keys"

# The keys must match the keys of the ParamChoice type, in kms.proto.
# More specifically, names must all be lower-case; e.g. "test" or "default"
[param_file_map]
test =  "parameters/small_test_params.json"
default = "parameters/default_params.json"