[package]
name = "simulator"
version = "0.7.1"
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.8", features = ["derive"] }
clap-stdin = "0.4.0"
config = "0.14.0"
cosmos-proto = { path = "../cosmos-proto" , version = "0.7.1" }
cosmwasm-std = { version = "2.0.2" }
events = { path = "../events" , version = "0.7.1" }
hex = "0.4.3"
kms = { path = "../../core/service", default-features = false, features = ["grpc-client", "non-wasm", "testing"] , version = "0.7.1" }
kms-blockchain-client = { path = "../client" , version = "0.7.1" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
tokio = { version = "1.37", features = ["rt-multi-thread"] }
tracing = { version = "~0.1", features = ["log"] }
tracing-subscriber = { version = "~0.3.16", features = ["env-filter", "fmt"] }
