[package]
name = "aipsc"
description = "Abstract Inclusion Proof Smart Contract with Interface definition and operations"
version = "0.9.0-rc3"
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
schema = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
events = { path = "../../events" , version = "0.9.0-rc3" }
schemars.workspace = true
serde.workspace = true
sylvia.workspace = true
sylvia-derive.workspace = true


