[package]
name = "aipsc"
description = "Abstract Inclusion Proof Smart Contract with Interface definition and operations"
version.workspace = true
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

# These libraries are necessary for make this a smart contract within Sylvia :
# https://cosmwasm.github.io/sylvia-book/basics/create-project.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
schema = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
sylvia.workspace = true
sylvia-derive.workspace = true
