storage_folder = "temp"
session_file = "experiment.bin"
params_file = "parameters/small_test_params.json"
setup_mode = "AllProtos"
decrypt_mode = "PRSSDecrypt"
number_messages = 10

[threshold_topology]
threshold = 1
peers = [
    { physical_address = "party-1.ddec.dev", physical_port = 50000, logical_address = "party-1.ddec.dev", logical_port = 50000 , id = 1 },
    { physical_address = "party-2.ddec.dev", physical_port = 50000, logical_address = "party-2.ddec.dev", logical_port = 50000 , id = 2 },
    { physical_address = "party-3.ddec.dev", physical_port = 50000, logical_address = "party-3.ddec.dev", logical_port = 50000 , id = 3 },
    { physical_address = "party-4.ddec.dev", physical_port = 50000, logical_address = "party-4.ddec.dev", logical_port = 50000 , id = 4 },
]
