choreo_use_tls = false

[protocol.host]
address = "localhost"
port = 50000
id = 1
choreoport = 60000

[tracing]
servicename = "moby"
endpoint = "http://localhost:4317"

[redis]
host = "redis://127.0.0.1"
