[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
kms-blockchain-connector = { path = "../connector" }
events = { path = "../events", features = ["subscription"] }
kms-blockchain-client = { path = "../client" }
kms = { path = "../../core/service", default-features = false, features = ["grpc-client"] }
ethers = { version = "2.0.14", features = ["abigen", "rustls", "ws", "ethers-solc", "legacy"] }
ethers-solc = "2.0.14"
tonic = "0.10"
prost = "0.12"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }
tempfile = "3.10.1"
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
serde_json = "1.0.117"
hex = "0.4.3"
futures = "0.3"
tracing = { version = "0.1.40", features = ["log"] }
eyre = "0.6.12"
thiserror = "1.0.61"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
retrying = { version = "0.1.0", features = ["tokio"] }
anyhow = "~1.0"
async-trait = "~0.1"
tokio-stream = "0.1.15"
tendermint = "0.35.0"
tendermint-rpc = { version = "0.35.0", features = ["websocket-client"] }
cosmrs = { version = "0.16.0", features = ["rpc", "dev", "cosmwasm", "bip32"] }
deep_space = "2.24.1"
secp256k1 = "0.29.0"
sha2 = "0.10.8"
hmac = "0.12.1"
strum = "0.26.2"
cosmos-proto = { path = "../cosmos-proto" }
cosmwasm-std = { version = "2.0.2" }
serde_asn1_der = "0.8.0"
backtrace = "0.3.72"
aes-prng = "0.2.1"
config = "0.14.0"
actix-web = "4.6.0"
bincode = "1.3.3"

[dev-dependencies]
alloy-sol-types = "0.7.0"
alloy-primitives = "0.7.0"
serial_test = "3.1.1"
test-context = "0.3.0"
test-utilities = { path = "../connector/utilities" }
rand = "0.8.5"

[build-dependencies]
tonic-build = "0.10"
