# .cargo/config.toml
[net]
git-fetch-with-cli = true

[alias]
wasm = "build --target wasm32-unknown-unknown --profile wasm --lib"
wasm-debug = "build --target wasm32-unknown-unknown --lib"
schema = "run --features schema schema"
