version: '3.8'

services:

  kms-core:
    image: ghcr.io/zama-ai/kms-dev:v0.3.2
    ports:
      - "50051:50051"

  fevm_full_node:
    image: ghcr.io/zama-ai/ethermint-dev-node:v0.2.4
    ports:
      - "26656:26656"
      - "26657:26657"
      - "8545:8545"
    volumes:
      - ./scripts/run_developer_image.sh:/start.sh
      - ./temp/:/config/res/keys/
    entrypoint: ["/bin/bash", "/start.sh"]
    healthcheck:
      test: "curl -f http://localhost:26657/status"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  fevm_light_node:
    image: cometbft/cometbft:v0.38.6
    ports:
      - "8888:8888"
    entrypoint: "/bin/bash"
    command: >
      -c "sleep 20;
      curl -s http://fevm_full_node:26657/commit | jq -r '.result.signed_header.commit.block_id.hash';
      cometbft light ethermint_9000-1 -p http://fevm_full_node:26657 -w http://fevm_full_node:26657 --hash $(curl -s http://fevm_full_node:26657/commit | jq -r '.result.signed_header.commit.block_id.hash') --height $(curl -s http://fevm_full_node:26657/commit | jq -r '.result.signed_header.header.height') --laddr tcp://0.0.0.0:8888 --sequential";
    depends_on:
      - fevm_full_node

  kms_full_node:
    image: cometbft/cometbft:v0.38.6
    ports:
      - "36657:36657"
    entrypoint: "/bin/bash"
    command: >
      -c "cometbft init;
      sed -i .back -re 's/^(cors_allowed_origins =.*)$.*/cors_allowed_origins = \[\"*\"\]/g' /cometbft/config/config.toml;
      cometbft unsafe_reset_all;
      cometbft node --rpc.laddr tcp://0.0.0.0:36657 --proxy_app=tcp://kms_chain:36658 --consensus.create_empty_blocks=false"
    depends_on:
      - kms_chain
    healthcheck:
      test: "curl -f http://localhost:36657/status"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  kms_light_node:
    image: cometbft/cometbft:v0.38.6
    ports:
      - "9999:9999"
    entrypoint: "/bin/bash"
    command: >
      -c "
      sleep 5;
      curl -s http://kms_full_node:36657/commit | jq -r '.result.signed_header.commit.block_id.hash';
      curl -s http://kms_full_node:36657/commit | jq -r '.result.signed_header.header.chain_id';
      cometbft light $(curl -s http://kms_full_node:36657/commit | jq -r '.result.signed_header.header.chain_id') -p http://kms_full_node:36657 -w http://kms_full_node:36657 --hash $(curl -s http://kms_full_node:36657/commit | jq -r '.result.signed_header.commit.block_id.hash') --height $(curl -s http://kms_full_node:36657/commit | jq -r '.result.signed_header.header.height') --laddr tcp://0.0.0.0:9999 --sequential"
    depends_on:
      - kms_full_node

  kms_chain:
    build:
      context: blockchain
      dockerfile: Dockerfile
    ports:
      - "36658:36658"
    entrypoint: /app/target/release/chain --host 0.0.0.0
    healthcheck:
      test: "netstat -an | grep 36658 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  blockexplorer:
    build:
      context: ./blockexplorer
    ports:
      - "8080:8080"
    depends_on:
      - kms_full_node
