[package]
name = "ethereum-inclusion-proofs"
version = "0.1.0"
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

# [dependencies]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
rlp = { version = "0.5.1", default-features = false }
trie-db = { version = "0.28.0", default-features = false }
hex-literal = "0.4.1"
num-bigint = "0.4"
primitive-types = { version = "0.12.0", default-features = false }
sha3.workspace = true
serde.workspace = true
serde_json.workspace = true
hex = { workspace = true, features = ["serde"] }
prost.workspace = true

# cosmwasm only dependencies
ethereum-triedb-local = { path = "../ethereum-triedb", version = "0.1.1", default-features = false, optional = true }
hash256-std-hasher = { version = "0.15.2", optional = true }
hash-db = { version = "0.16.0", default-features = false, optional = true }

# Default only dependencies
ethereum-triedb = { version = "=0.1.1", optional = true }
reqwest = { workspace = true, features = ["json"], optional = true }

[features]
cosmwasm = ["ethereum-triedb-local", "hash256-std-hasher", "hash-db"]
default = ["ethereum-triedb", "reqwest"]

[lints.clippy]
doc_lazy_continuation = "allow"

# Add dev dependencies
[dev-dependencies]
tokio.workspace = true
