[package]
name = "backward-compatibility"
version = "0.9.0-rc25"
publish = false
authors = ["Zama"]
edition = "2021"
license = "BSD-3-Clause-Clear"

[dependencies]
# This is a list of kms-core versions we will generate data for. This list will grow over time.
# They are only activated when generating data, with the binary target and the "generate" feature.
kms_0_9 = { git = "ssh://git@github.com/zama-ai/kms-core.git", package = "kms", rev = "00e4bd81b84a7dc20a161d3c76dbda2511d20bca", optional = true }
distributed_decryption_0_9 = { git = "ssh://git@github.com/zama-ai/kms-core.git", package = "distributed-decryption", rev = "00e4bd81b84a7dc20a161d3c76dbda2511d20bca", optional = true, features = [
    "testing",
] }
events_0_9 = { git = "ssh://git@github.com/zama-ai/kms-core.git", package = "events", rev = "00e4bd81b84a7dc20a161d3c76dbda2511d20bca", optional = true }

# Dependencies for the 0.9 version
# Note: these dependencies should match the versions used by the KMS and distributed decryption
# modules as much as possible to avoid serialization differences
tfhe_versionable_0_3 = { package = "tfhe-versionable", version = "0.3.1", optional = true }
tfhe_0_8 = { package = "tfhe", version = "0.8.2", optional = true, features = [
    "shortint",
] }
serde = { version = "=1.0.214", features = ["derive"] }
strum = { version = "=0.26.3", features = ["derive"] }
semver = { version = "=1.0.23", optional = true }
ron = { version = "=0.8.1", features = ["integer128"] }
bincode = "=1.3.3"
aes-prng = "=0.2.1"
rand = "=0.8.5"
tokio = { version = "=1.41.0", features = ["full"] }

[[bin]]
name = "backward-compatibility"
required-features = ["generate"]

# Note: The `generate` feature should not be put by default to avoid dependency conflicts.
[features]
generate = [
    "dep:kms_0_9",
    "dep:distributed_decryption_0_9",
    "dep:events_0_9",
    "dep:tfhe_versionable_0_3",
    "dep:tfhe_0_8",
]
load = ["dep:semver"]
tests = []
