[backend.aws.big-instance]
region = "eu-west-3"
image_id = "ami-0a56cf46caf2fd41c"
instance_type = "m6i.4xlarge"

[backend.aws.docker-big-instance]
region = "eu-west-3"
image_id = "ami-0a56cf46caf2fd41c"
instance_type = "c6i.8xlarge"
