# Configuration for the KMS peers
# This is used to define the number of peers and their IDs
kmsPeers:
  # Defines either the peer ID when count=1 or the start ID of a set of peers when count>1
  id: 1
  # The number of peers managed by the StatefulSets
  count: 1

# Configuration for the KMS connector
# This is used to define the connector configuration
kmsConnector:
  # Add the following to enable the connector:
  enabled: true
  # Override the name of the connector:
  nameOverride:
  # Override the image of the connector:
  image:
    name: ghcr.io/zama-ai/kms-connector
    # Override the tag of the connector:
    tag: latest
  # Define all the environment variable needed for the connector:
  env:
    - name: PROBE
      value: "true"
    - name: KMS_CONNECTOR_GWL2_URL
      value: "ws://layer2-node:8546"
    - name: KMS_CONNECTOR_MNEMONIC
      value: "coyote sketch defense hover finger envelope celery urge panther venue verb cheese"
    - name: KMS_CONNECTOR_CHAIN_ID
      value: "54321"
    - name: KMS_CONNECTOR_DECRYPTION_MANAGER_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: kms-sc-deploy-kms-sc-addresses
          key: DECRYPTION_MANAGER_CONTRACT_ADDRESS
    - name: KMS_CONNECTOR_HTTPZ_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: kms-sc-deploy-kms-sc-addresses
          key: HTTPZ_CONTRACT_ADDRESS
    - name: KMS_CONNECTOR_CHANNEL_SIZE
      value: "1000"
    - name: KMS_CONNECTOR_SERVICE_NAME
      value: "kms-connector"
    - name: KMS_CONNECTOR_DECRYPTION_TIMEOUT_SECS
      value: "300"
    - name: KMS_CONNECTOR_REENCRYPTION_TIMEOUT_SECS
      value: "300"
    - name: KMS_CONNECTOR_RETRY_INTERVAL_SECS
      value: "5"
    - name: KMS_CONNECTOR_S3_CONFIG__REGION
      value: "us-east-1"
    - name: KMS_CONNECTOR_S3_CONFIG__BUCKET
      value: "my-ciphertext-bucket"
    - name: KMS_CONNECTOR_S3_CONFIG__ENDPOINT
      value: "http://localhost:9876"
    - name: KMS_CONNECTOR_VERIFY_COPROCESSORS
      value: "true"
    - name: KMS_CONNECTOR_PRIVATE_KEY
      value: "0x3f45b129a7fd099146e9fe63851a71646231f7743c712695f3b2d2bf0e41c774"
  # Define the storage for the connector:
  storage:
    storageClassName: gp3
    capacity: 5Gi
  # Define the node selector for the connector:
  nodeSelector:
  # Define the affinity for the connector:
  affinity:
  # Define the tolerations for the connector:
  tolerations:

kmsCore:
  # Add the following to enable the core:
  enabled: true
  # Override the name of the core:
  nameOverride:
  # Override the address of the core:
  addressOverride:
  # Override the image of the core:
  image:
    name: ghcr.io/zama-ai/kms-service
    tag: latest
    pullPolicy: Always
  # Define the service account name for the core:
  serviceAccountName:
  # Define the environment variables for the core:
  envFrom:
    configmap:
      name:
  # Add the following to enable threshold mode:
  thresholdMode:
    enabled: false
    # If left unset, the chart will generate the list automatically based on pod replicas of the statefulset
    peersList:
    #  - id: 1
    #    host: kms-service-core-1
    #    port: 50001
    #  - id: 2
    #    host: kms-service-core-2
    #    port: 50001
    dec_capacity: 10000
    min_dec_cache: 6000
    num_sessions_preproc: 2
    decryption_mode: "NoiseFloodSmall"
  # Add the following to enable nitro enclave:
  # Nitro enclave needs specific instance types
  nitroEnclave:
    enabled: false
    debug: true
    # Enclave CPU count, must be a multiple of 2 since whole cores (not hyperthreads) are sliced off and dedicated to the enclave
    cpuCount: 6
    # Enclave Memory in GiB
    memoryGiB: 20
    cid: 20
    eifPath: /app/kms/core/service/enclave.eif
    userId: 10003
    groupId: 10002
    ports:
      tracing: 4317
      # For AWS authentication, set the `imds` or `sts` ports
      # To authenticate using either IMDS (with the Kubernetes node EC2 instance role) or STS (with the IRSA)
      imds: 5000
      sts: 5500
      s3: 6000
      awskms: 7000
      peer: 10000
      # Important, don't bind to port 9000 as it is reserved by Nitro for communicating with the enclave.
  publicVault:
    s3:
      enabled: true
      bucket: kms-public
      path: kms
  privateVault:
    s3:
      enabled: false
      bucket: kms-private
      path: kms
    awskms:
      enabled: false
      keychain: awskms://symm/00000000-0000-0000-0000-000000000000
  aws:
    roleArn:
    region: eu-west-1
  storage:
    # storageClassName: gp3
    capacity: 5Gi
  ports:
    client: 50100
    peer: 50001
    metrics: 9646
  workdir: /root
  serviceMonitor:
    enabled: false
  # Note: these requests/limits is only for non-enclave workloads, this will not be allocated to the kms-core process running in Nitro
  resources:
    requests: {}
      # memory: 1Gi
      # cpu: 1
    limits:
      # memory: 30Gi
      ephemeralStorage: 1Gi
      grpcTimeout: 360
      grpcMaxMessageSize: 2097520
  nodeSelector:
  affinity:
  tolerations:
mtls:
  enabled: false

kmsCoreClient:
  enabled: false
  nameOverride:
  image:
    name: ghcr.io/zama-ai/kms-core-client
    tag: latest
  envFrom:
    configmap:
      name:
  num_majority: 2
  num_reconstruct: 3
  decryption_mode: "NoiseFloodSmall"
  fhe_parameter: Test
  resources:
    requests: {}
      # memory: 1Gi
      # cpu: 1
    limits: {}
      # memory: 30Gi
      # cpu: 1
  nodeSelector:
  affinity:
  tolerations:

kmsInit:
  enabled: false
  nodeSelector:
  affinity:
  tolerations:

kubeUtils:
  image:
    name: ghcr.io/zama-ai/kube-utils
    tag: 0.2.0
    pullPolicy: Always

runMode: dev

redis:
  enabled: false
  host: "redis://redis-master.common.svc.cluster.local"

tracing:
  enabled: false
  endpoint: "http://otel-deployment-opentelemetry-collector.observability.svc.cluster.local:4317"
  otlp_timeout_ms: 10000

minio:
  enabled: false
  fullnameOverride: minio
  auth:
    rootUser: minio-admin
    rootPassword: minio-admin
  provisioning:
    enabled: true
    buckets:
      - name: kms-public
        region: eu-west-1
    users:
      - username: kms-access-key-id
        password: kms-secret-access-key
        policies:
          - readwrite
    extraCommands:
      - "mc anonymous set public provisioning/kms-public"

rustLog: info

podSecurityContext:
  # To set when the image will support non root user
  #  runAsUser: 1000
  #  runAsGroup: 1000
  #  fsGroup: 1000
  #  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  privileged: false

podSecurityContextForEnclave:
  fsGroup: 1001     # Keep this as 1001 to match device group
  supplementalGroups: [1001]  # Add device group as supplemental

kyverno:
  enabled: false

# Cronjob kubernetes
kmsCoreClientTesting:
  enabled: false
  schedule: "*/5 * * * *"
  shell_command:
  storage:
    storageClassName: gp3
    capacity: 1Gi
