kmsPeers:
  # Number of replicas managed by each statefulset
  count: 4

kmsConnector:
  enabled: false

kmsCoreClient:
  enabled: true
  nameOverride: kms-core-client-threshold-staging
  image:
    name: ghcr.io/zama-ai/kms-core-client
    tag: v0.11.0-rc2

kmsCore:
  nameOverride: kms-threshold-staging
  addressOverride:
  image:
    name: ghcr.io/zama-ai/kms-service
    tag: v0.11.0-rc2
  thresholdMode:
    enabled: true
    initializationScript:
      enabled: true
#    peersList:
#      - id: 1
#        host: kms-threshold-staging-1
#        port: 50001
#      - id: 2
#        host: kms-threshold-staging-2
#        port: 50001
#      - id: 3
#        host: kms-threshold-staging-3
#        port: 50001
#      - id: 4
#        host: kms-threshold-staging-4
#        port: 50001
  aws:
    region: eu-west-1
  storage:
    capacity: 5Gi
  serviceMonitor:
    enabled: false
  resources:
    requests:
      memory: 2Gi
      cpu: 2
    limits:
      memory: 4Gi
      ephemeralStorage: 1Gi
      grpcTimeout: 360
      grpcMaxMessageSize: 2097520

environment: dev

rustLog: info

minio:
  enabled: true

kyverno:
  enabled: false
