name: zama-kms

services:

  gateway:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:latest
    command:
      - "gateway"
    environment:
      - GATEWAY__ETHEREUM__LISTENER_TYPE=FHEVM_V1_1
      - GATEWAY__ETHEREUM__WSS_URL=ws://FHE_VALIDATOR_HOST:FHE_VALIDATOR_PORT
      - GATEWAY__ETHEREUM__FHE_LIB_ADDRESS=000000000000000000000000000000000000005e
      - GATEWAY__ETHEREUM__RELAYER_ADDRESS=97F272ccfef4026A1F3f0e0E879d514627B84E68
      - GATEWAY__ETHEREUM__ORACLE_PREDEPLOY_ADDRESS=c8c9303Cd7F337fab769686B593B87DC3403E0cd
      - GATEWAY__ETHEREUM__TEST_ASYNC_DECRYPT_ADDRESS=99F460504563579922352932A42172B3c04a1400
      - GATEWAY__KMS__TENDERMINT_NODE_ADDR=http://KMS_VALIDATOR_HOST:KMS_VALIDATOR_HTTP_PORT
      - GATEWAY__KMS__CONTRACT_ADDRESS=wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d
      - GATEWAY__KMS__MNEMONIC="some mnemonic wallet"
      - GATEWAY__KMS__ADDRESS=http://KMS_VALIDATOR_HOST:KMS_VALIDATOR_GRPC_PORT
      - GATEWAY__KMS__KEY_ID=04a1aa8ba5e95fb4dc42e06add00b0c2ce3ea424
      - GATEWAY__STORAGE__URL=http://kv-store:8088
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://KMS_VALIDATOR_HOST:KMS_VALIDATOR_GRPC_PORT
      - ASC_CONN__BLOCKCHAIN__CONTRACT=SAME_AS_GATEWAY__KMS__CONTRACT_ADDRESS


  kv-store:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:latest
    command:
      - "kv_store"
    ports:
      - "8088:8088"


