name: zama-gateway

services:

  gateway:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:c22a5b7
    command:
      - "gateway"
    environment:
      - GATEWAY__ETHEREUM__LISTENER_TYPE=FHEVM_V1_1
      - GATEWAY__ETHEREUM__WSS_URL=ws://FHEVM_VALIDATOR_HOST:FHEVM_VALIDATOR_PORT
      - GATEWAY__ETHEREUM__FHE_LIB_ADDRESS=000000000000000000000000000000000000005d
      - GATEWAY__ETHEREUM__ORACLE_PREDEPLOY_ADDRESS=c8c9303Cd7F337fab769686B593B87DC3403E0cd
      - GATEWAY__KMS__ADDRESS=http://localhost:9090
      - GATEWAY__KMS__KEY_ID=04a1aa8ba5e95fb4dc42e06add00b0c2ce3ea424
      - GATEWAY__STORAGE__URL=http://localhost:8088
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://localhost:9090



