[package]
name = "cosmos-proto"
version = "0.5.0"
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
tonic = "0.11.0"
prost = "0.12.4"
prost-types = "0.12.4"

[build-dependencies]
tonic-build = "0.11"
prost-build = "0.12.4"
glob = "0.3.1"



