[package]
name = "cosmos-proto"
version = "0.1.1"
edition = "2021"

[dependencies]
tonic = "0.11.0"
prost = "0.12.4"
prost-types = "0.12.4"

[build-dependencies]
tonic-build = "0.11"
prost-build = "0.12.4"
glob = "0.3.1"



