[package]
name = "conf-trace"
version = "0.9.0-rc19"
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
config = "0.14.0"
lazy_static = "1.5"
opentelemetry = "0.23"
opentelemetry-http = "0.12"
opentelemetry-otlp = { version = "0.16.0", features = ["tokio"] }
opentelemetry-prometheus = "0.16.0"
opentelemetry-semantic-conventions = "0.15.0"
opentelemetry-stdout = { version = "0.4.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.23", features = ["rt-tokio","logs"]}
prometheus = "=0.13.4"
serde = { workspace = true, features = ["derive", "rc"] }
strum = "0.26"
strum_macros = "0.26"
tonic.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = "0.24"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
typed-builder.workspace = true
