[package]
name = "conf-trace"
version.workspace = true
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
config = "0.14.1"
lazy_static.workspace = true
opentelemetry.workspace = true
opentelemetry-http = "0.12"
opentelemetry-otlp = { version = "0.16.0", features = ["tokio"] }
opentelemetry-prometheus = "0.16.0"
opentelemetry-semantic-conventions = "0.15.0"
opentelemetry-stdout = { version = "0.4.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.23", features = ["rt-tokio","logs"]}
prometheus = "=0.13.4"
serde = { workspace = true, features = ["derive", "rc"] }
strum.workspace = true
strum_macros.workspace = true
tonic.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
typed-builder.workspace = true
