[config]
unstable_features = ["CTRL_C_HANDLING"]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

###Generic commands to be used for local deployment with docker
#Build the image for TFHE parties, with testing feature to allow centralized DKG
#NOTE(Titouan): I believe testing feature doesn't have any real impact on performances, it's mostly to avoid having testing code silently spill
#into production.
[tasks.tfhe-docker-image]
command = "docker"
args = ["build", "-f", "../../docker/core/threshold/local.dockerfile", "--build-arg", "FEATURES=testing,choreographer", "-t", "tfhe-core", "../../"]

#Build the image for BGV parties (with centralized DKG available)
[tasks.bgv-docker-image]
command = "docker"
args = ["build", "-f", "../../docker/core/threshold/local.dockerfile", "--build-arg", "FEATURES=experimental,choreographer", "-t", "bgv-core", "../../"]

#Generate the certificate for TLS communication of the parties
[tasks.gen-test-certs]
command = "cargo"
args = ["run", "--manifest-path=../service/Cargo.toml", "--release", "--bin", "kms-gen-tls-certs", "--", "--ca-prefix", "p", "--ca-count", "${NUM_PARTIES}", "-o", "test_certs"]

#Generate the toml config file for the choreographer for a cluster of parties accessible from localhost
[tasks.gen-local-choreo]
command = "cargo"
args = ["run", "--bin", "gen-experiment", "--release", "--features", "templating", "--", "-n", "${NUM_PARTIES}", "-t", "${THRESHOLD}", "-f", "temp", "-o", "local-cluster", "choreographer"]

#Generate the yml config file for the dockerized parties
[tasks.tfhe-gen-local-cluster]
command = "cargo"
args = ["run", "--bin", "gen-experiment", "--release", "--features", "templating", "--", "-n", "${NUM_PARTIES}", "-o", "tfhe-local-cluster", "-f", "temp", "parties", "--protocol", "tfhe"]

#Generate the yml config file for the dockerized parties
[tasks.bgv-gen-local-cluster]
command = "cargo"
args = ["run", "--bin", "gen-experiment", "--release", "--features", "templating", "--", "-n", "${NUM_PARTIES}", "-o", "bgv-local-cluster", "-f", "temp", "parties", "--protocol", "bgv"]

#Generate docker-compose file for the TFHE parties as well as the toml config file for the choreogrpaher for a local deployment
[tasks.tfhe-gen-experiment]
command = "cargo"
args = ["run", "--bin", "gen-experiment", "--features", "templating", "--", "-n", "${NUM_PARTIES}", "-t", "${THRESHOLD}", "-f", "temp", "-o", "${EXPERIMENT_NAME}", "all", "--protocol", "tfhe" ]

#Generate docker-compose file for the BGV parties as well as the toml config file for the choreogrpaher for a local deployment
[tasks.bgv-gen-experiment]
command = "cargo"
args = ["run", "--bin", "gen-experiment", "--features", "templating", "--", "-n", "${NUM_PARTIES}", "-t", "${THRESHOLD}", "-f", "temp", "-o", "${EXPERIMENT_NAME}" , "all", "--protocol", "bgv"]


#Bring parties alive based on provided yml file
[tasks.start-parties]
command = "docker"
args = ["compose", "--progress=quiet", "-f", "temp/${EXPERIMENT_NAME}.yml", "up", "--quiet-pull"]

#Stop all parties
[tasks.stop-parties]
script = '''
docker compose -f temp/${EXPERIMENT_NAME}.yml logs > temp/${EXPERIMENT_NAME}.log
docker compose --progress=quiet -f temp/${EXPERIMENT_NAME}.yml down
'''


###One liner for benching everything
[tasks.experiment-name]
script = '''
echo ""
echo ""
echo "========================================================="
echo "=                                                       ="
echo "= Experiment: ${EXPERIMENT_NAME}                        "
echo "=                                                       "
echo "= Parties: ${NUM_PARTIES}                               "
echo "= Threshold: ${THRESHOLD}                               "
echo "=                                                       ="
echo "========================================================="
echo ""
echo ""
'''

#Shut down the parties and do some file management
[tasks.shutdown]
script = '''
mkdir -p temp/stats
docker stats --no-stream > temp/stats/${EXPERIMENT_NAME}_$(date +%Y_%m_%d-%H:%M:%S).log
docker compose -f temp/${EXPERIMENT_NAME}.yml logs > temp/${EXPERIMENT_NAME}.log
docker compose --progress=quiet -f temp/${EXPERIMENT_NAME}.yml down
mkdir -p temp/telemetry/archived
mv temp/telemetry/export.json temp/telemetry/archived/trace_${EXPERIMENT_NAME}_$(date +%Y_%m_%d-%H:%M:%S).json
'''

[tasks.setup]
script = '''
mkdir -p temp/telemetry
echo "" > temp/telemetry/export.json
chmod o+w temp/telemetry/export.json
'''

#Bring parties alive based on provided yml file, waiting for health check to pass
[tasks.start-parties-healthy]
command = "docker"
args = ["compose", "--progress=quiet", "-f", "temp/${EXPERIMENT_NAME}.yml", "up", "--quiet-pull", "--wait"]

#Run the full test suite for tfhe with real dkg
[tasks.tfhe-test-real-dkg]
command = "sh"
args = ["test_scripts/tfhe_test_script_real_dkg.sh", "temp/${EXPERIMENT_NAME}.toml"]

#Run the full test suite for tfhe with centralized dkg
[tasks.tfhe-test-fake-dkg]
command = "sh"
args = ["test_scripts/tfhe_test_script_fake_dkg.sh", "temp/${EXPERIMENT_NAME}.toml"]

#Run the full test suite for tfhe with real dkg
[tasks.bgv-test-real-dkg]
command = "sh"
args = ["test_scripts/bgv_test_script_real_dkg.sh", "temp/${EXPERIMENT_NAME}.toml"]

#Run the full test suite for tfhe with centralized dkg
[tasks.bgv-test-fake-dkg]
command = "sh"
args = ["test_scripts/bgv_test_script_fake_dkg.sh", "temp/${EXPERIMENT_NAME}.toml"]



##For TFHE we set NUM_PARTIES to 5 to be able to test both small and large sessions
[tasks.tfhe-bench-fake-dkg]
env = {"NUM_PARTIES" = "4", THRESHOLD = "1", EXPERIMENT_NAME="tfhe-fake-dkg-bench"}
run_task = { name = ["setup", "gen-test-certs", "tfhe-gen-experiment", "experiment-name", "start-parties-healthy", "tfhe-test-fake-dkg"], fork = true, cleanup_task = "shutdown" }

[tasks.tfhe-bench-real-dkg]
env = {"NUM_PARTIES" = "5", THRESHOLD = "1", EXPERIMENT_NAME="tfhe-real-dkg-bench"}
run_task = { name = ["setup", "gen-test-certs", "tfhe-gen-experiment", "experiment-name", "start-parties-healthy", "tfhe-test-real-dkg"], fork = true, cleanup_task = "shutdown" }

##For BGV we set NUM_PARTIES to 4 as we only need small sessions
[tasks.bgv-bench-fake-dkg]
env = {"NUM_PARTIES" = "4", THRESHOLD = "1", EXPERIMENT_NAME="bgv-fake-dkg-bench"}
run_task = { name = ["setup", "gen-test-certs", "bgv-gen-experiment", "experiment-name", "start-parties-healthy", "bgv-test-fake-dkg"], fork = true, cleanup_task = "shutdown" }

[tasks.bgv-bench-real-dkg]
env = {"NUM_PARTIES" = "4", THRESHOLD = "1", EXPERIMENT_NAME="bgv-real-dkg-bench"}
run_task = { name = ["setup", "gen-test-certs", "bgv-gen-experiment", "experiment-name", "start-parties-healthy", "bgv-test-real-dkg"], fork = true, cleanup_task = "shutdown" }


###Commands used by the CI
#Build the docker image based on bench.dockerfile (which has the testing feature for centralized dkg)
[tasks.docker-image-ci]
command = "docker"
args = ["build", "--build-arg=CONCRETE_ACTIONS_TOKEN=${CONCRETE_ACTIONS_TOKEN}", "-f", "../../docker/core/threshold/bench.dockerfile", "-t", "tfhe-core", "../../"]

[tasks.ci-test]
run_task = { name = ["docker-image-ci", "grpc-bench"] }
