name: "[core/backup PR] Pipeline Run"

on:
  pull_request:
    paths:
      - 'core/backup/**'
      - '.github/workflows/backup-pr.yml'

concurrency:
  group: backup-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core/backup'
      args-tests-fhe: ''
      args-tests: '--all-features'
      package-name: 'kms-backup'
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - build
