name: "[Blockchain-Gateway-PR] Pipeline Run"

on:
  pull_request:
    branches: ['*']
    paths:
      - 'blockchain/gateway/**'
      - 'blockchain/client/**'
      - 'blockchain/events/**'
      - '.github/workflows/blockchain-gateway-pr.yml'

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './blockchain/gateway'
      args-tests-fhe: ''
      package-name: 'gateway'
      test-coverage: true
      test-minimum-coverage: 10
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: write
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}


  docker:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./blockchain/gateway"
      push_image: false
      image-name: 'kms-blockchain-gateway'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - build
      - docker

