name: "[Blockchain-Simulator-Merge Main] Pipeline Run"

on:
  push:
    branches: ['main']
    paths:
      - 'blockchain/**'
      - 'core/**'
      - 'conf-trace/**'
      - '.github/workflows/blockchain-simulator-main.yml'

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './blockchain/simulator'
      args-tests-fhe: ''
      package-name: 'simulator'
    permissions:
      contents: 'write'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./blockchain/simulator"
      push_image: true
      image-name: 'kms-blockchain-simulator'
      image-dev-name: 'kms-blockchain-simulator-dev'
      generate-dev-image: false
      image-dev-description: 'KMS Blockchain Simulator Dev Docker Image'
      arm-build: true
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}


  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - build
      - docker

