name: "[Blockchain-Connector-Merge Main] Pipeline Run"

on:
  schedule:
    - cron: '0 0 * * 1-5' # 00:00 UTC is 01:00 CET every weekday
  workflow_call:
  push:
    branches: ['main']
    paths:
      - 'blockchain/client/**'
      - 'blockchain/connector/**'
      - 'blockchain/events/**'
      - 'conf-trace/**'
      - 'core/grpc/**'
      - '.github/workflows/blockchain-connector-main.yml'

concurrency:
  group: blockchain-connector-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './blockchain/connector'
      args-tests: '-F slow_tests'
      package-name: 'kms-blockchain-connector'
    permissions:
      contents: 'write'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./blockchain/connector"
      push_image: true
      image-name: 'kms-blockchain-connector'
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - build
      - docker
