# Lint and check CI
name: "[CI Lint and Checks]"

on:
  pull_request:

env:
  ACTIONLINT_VERSION: 1.6.27

jobs:
  lint-check:
    name: Lint and checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: actionlint
        uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821 # v2.0.0

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ed00f72a3ca5b6eff8ad4d3ffdcacedb67a21db1 # v3.0.15
