name: Cargo Workspaces Release

on:
  workflow_call:
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
    inputs:
      version:
        type: string
        required: true

jobs:
  cargo-workspaces-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

      - name: Force git update
        run: |
          git checkout main
          git fetch origin
          git merge origin/main

      - name: Install semantic-release-cargo
        uses: taiki-e/install-action@v2
        with:
          tool: semantic-release-cargo@2

      - name: Prepare semantic-release for Rust
        run: semantic-release-cargo prepare ${{ inputs.version }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci skip] Apply new verion ${{ inputs.version }} to Cargo.toml files"
          commit_user_name: zama-bot
          commit_user_email: kms-infra@zama.ai
          push_options: --force

