name: Compile Rust Project and Run Tests

on:
  workflow_call:
    inputs:
      build-publish-docs:
        type: boolean
        required: false
        default: false
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
      args_build:
        type: string
        required: false
        default: '--lib'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  compile-rust-unit-tests:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Home
        if: ${{ inputs.runs-on != 'ubuntu-latest' }}
        run: echo "HOME=/home/ubuntu" >> ${GITHUB_ENV}

      - name: Set up Rust.
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Setup usage of private repo
        run: git config --global url."https://${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Linting
        run: cargo clippy --all-targets --workspace -- -D warnings

      - name: Run Tests
        run: cargo test ${{ inputs.args_build }} -F tfhe/seeder_unix -F tfhe/x86_64 --release

      - name: Install wasm-pack
        run: wasm-pack --version > /dev/null 2>&1 || cargo install wasm-pack

      - name: Build wasm
        run: RUSTFLAGS="$RUSTFLAGS -A dead_code -A unused_imports" wasm-pack build --target web . --no-default-features

      - name: Build Documentation
        if: ${{ inputs.build-publish-docs }}
        run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --no-deps

      - name: Deploy to GitHub Pages
        if: ${{ inputs.build-publish-docs }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
