name: Cargo Workspaces Release

on:
  workflow_call:
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
    inputs:
      version:
        type: string
        required: true

jobs:
  cargo-workspaces-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
          token: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

      - name: Force git update
        run: |
          git checkout main
          git fetch origin
          git merge origin/main

      - name: Install semantic-release-cargo
        uses: taiki-e/install-action@437c908c7e5ee18b63a261286cbe5147219f8a39 # v2.44.44
        with:
          tool: semantic-release-cargo@2

      - name: Prepare semantic-release for Rust
        run: semantic-release-cargo prepare ${{ inputs.version }}

      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 #v5.0.1
        with:
          commit_message: "[ci skip] Apply new version ${{ inputs.version }} to Cargo.toml files"
          commit_user_name: zama-bot
          commit_user_email: kms-infra@zama.ai
          push_options: --force
