name: Cargo Workspaces Release

on:
  workflow_call:
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
    inputs:
      version:
        type: string
        required: true

jobs:
  cargo-workspaces-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "26.x"

      - name: Setup usage of private repo
        run: git config --global url."https://${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Install Cargo Workspaces
        run: cargo install cargo-workspaces

      - name: Generating Release on Cargo Manifests
        run: cargo workspaces version -y -m "[ci skip] Release Version ${{ inputs.version }}" --no-individual-tags --no-git-push custom ${{ inputs.version }}

      - uses: stefanzweifel/git-auto-commit-action@v5
