name: Cargo Workspaces Release

on:
  workflow_call:
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
    inputs:
      version:
        type: string
        required: true

jobs:
  cargo-workspaces-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install Cargo Workspaces
        run: cargo install cargo-workspaces

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}'
          name: 'zama-bot'
          actor: 'zama-bot'
          email: 'kms-infra@zama.ai'

      - name: Generating Release on Cargo Manifests
        run: cargo workspaces version -y -m "Release Version ${{ inputs.version }}" --no-git-tag custom ${{ inputs.version }}

