name: Run Docker On Big Instance
on:
  workflow_call:
    inputs:
      args-tests:
        type: string
        required: true
        default: ''
      working-directory:
        type: string
        required: true
        default: ''
      build-publish-docs:
        type: boolean
        required: false
        default: false
      run-redis:
        type: boolean
        required: false
        default: false
    secrets:
      SLAB_ACTION_TOKEN:
        required: true
      SLAB_BASE_URL:
        required: true
      JOB_SECRET:
        required: true
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: zama-ai/slab-github-runner@f3a88ba3074b9cbf77857f6c4d8849c3b01b5ff9
        with:
          mode: start
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          region: eu-west-3
          ec2-image-id:	ami-006a9a76dbf4d880c
          ec2-instance-type: m6i.4xlarge
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}

  run-build:
    needs: start-runner
    uses: ./.github/workflows/common-build.yml
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
    with:
      runs-on: ${{ needs.start-runner.outputs.label }}
      build-publish-docs: ${{ inputs.build-publish-docs }}
      working-directory: ${{ inputs.working-directory }}
      args-tests: ${{ inputs.args-tests }}
      run-redis: ${{ inputs.run-redis }}

  stop-runner:
    name: Stops self-hosted EC2 runner
    needs:
      - start-runner
      - run-build
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Stop EC2 runner
        uses: zama-ai/slab-github-runner@f3a88ba3074b9cbf77857f6c4d8849c3b01b5ff9
        with:
          mode: stop
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          region: eu-west-3
          label: ${{ needs.start-runner.outputs.label }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}


