name: Deploy to AWS ECS
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      image_eif:
        type: string
        required: true
      eif_pcr0:
        type: string
        required: false
        default: ''
    secrets:
      AWS_ACCESS_KEY_ID_TERRAFORM:
        required: true
      AWS_SECRET_ACCESS_KEY_TERRAFORM:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform Cli
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}
          aws-region: eu-west-3

      - name: Current branch sha
        if: github.event_name != 'release'
        run: |
          echo "NAMESPACE=dev" >> $GITHUB_ENV
      - name: Current Tag
        if: github.event_name == 'release'
        run: |
          echo "NAMESPACE=prod" >> $GITHUB_ENV

      - name: Initialize terraform
        run: terraform -chdir=operations/terraform/environments/${{env.NAMESPACE}} init

      - name: Execute Plan terraform
        run: terraform -chdir=operations/terraform/environments/${{env.NAMESPACE}} plan -var='image=${{ inputs.image_name }}' -var='image_eif=${{ inputs.image_eif }}' -var='eif_pcr0=${{ inputs.eif_pcr0 }}'

      - name: Apply terraform
        run: terraform -chdir=operations/terraform/environments/${{env.NAMESPACE}} apply -var='image=${{ inputs.image_name }}' -var='image_eif=${{ inputs.image_eif }}' -var='eif_pcr0=${{ inputs.eif_pcr0 }}' -auto-approve

      - name: Output terraform
        run: terraform -chdir=operations/terraform/environments/${{env.NAMESPACE}} output

