name: Test Wasm Optimization

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      cargo-manifest-path:
        type: string
        required: false
        default: './'
      target-path:
        type: string
        required: false
        default: ''
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  optimize-wasm-files:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Home
        if: ${{ inputs.runs-on != 'ubuntu-latest' }}
        run: echo "HOME=/home/ubuntu" >> "${GITHUB_ENV}"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          rustflags: '-C link-arg=-s'

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

      - name: Build Wasm files
        run: |
          cargo build --target wasm32-unknown-unknown --release --lib --manifest-path ${{ inputs.cargo-manifest-path }}Cargo.toml

      - name: Optimize Wasm files
        uses: NiklasEi/wasm-opt-action@c21a6d6a7c61df2b9dc3870c75ed9bf943e645df # v2.3.3
        with:
          file: ${{ inputs.working-directory }}${{ inputs.target-path }}target/wasm32-unknown-unknown/release/*.wasm
          optimize_all: true
