name: Docker Build and Push with Multiarch Manifest

on:
  workflow_call:
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
      AWS_ACCESS_KEY_S3_USER:
        required: true
      AWS_SECRET_KEY_S3_USER:
        required: true
    inputs:
      ref:
        type: string
        required: false
        default: ''
      working-directory:
        type: string
        required: true
      docker-context:
        type: string
        required: false
        default: '.'
      image-name:
        type: string
        required: true
      push_image:
        type: boolean
        default: true
        required: false
      runs-on-amd:
        type: string
        required: false
        default: 'ubuntu-latest'
      runs-on-arm:
        type: string
        required: false
        default: 'large_ubuntu_16_arm'
      docker-file:
        type: string
        default: 'ci.dockerfile'
        required: false
      cache-from:
        type: string
        required: false
        default: 'type=gha'
      cache-to:
        type: string
        required: false
        default: 'type=gha,mode=max'
      app-cache-dir:
        type: string
        required: true
    outputs:
      image_name:
        description: "Image Name with Tag generated by this task"
        value: "${{ jobs.create-manifest.outputs.image_name }}"
      image_tag:
        description: "Docker Tag generated by this task"
        value: "${{ jobs.determine-tag.outputs.docker_tag }}"

env:
  RUST_IMAGE_VERSION: '1.85.0'

jobs:
  determine-tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Docker Tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "tag=nightly-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_OUTPUT"
          fi

  build-and-push-docker:
    needs: determine-tag
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ${{ inputs.runs-on-amd }}
            platform-tag: amd64
          - platform: linux/arm64
            runs-on: ${{ inputs.runs-on-arm }}
            platform-tag: arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: 'true'
          token: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          platforms: ${{ matrix.platform }}


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
          aws-region: eu-west-3



      ############################################################################
      # Setup cache for dockerfile and inject in docker
      #
      - name: Setup Cache
        uses: runs-on/cache@197b09d6da1bf42f673fee18769c794b789a0c7d # v4
        id: cache
        env:
          RUNS_ON_S3_BUCKET_CACHE: gh-actions-cache-eu-west-3
          RUNS_ON_AWS_REGION: eu-west-3
        with:
          path: |
            var-cache-apt
            var-lib-apt
            usr-local-cargo-registry
            usr-local-cargo-git
            usr-local-cargo-bin
            usr-local-cargo-registry-index
            usr-local-cargo-registry-cache
            usr-local-cargo-git-db
            app-${{ inputs.app-cache-dir }}-target
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            /sccache
          key: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
        with:
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "usr-local-cargo-registry": "/usr/local/cargo/registry",
              "usr-local-cargo-git": "/usr/local/cargo/git",
              "usr-local-cargo-bin": "/usr/local/cargo/bin",
              "usr-local-cargo-registry-index": "/usr/local/cargo/registry/index",
              "usr-local-cargo-registry-cache": "/usr/local/cargo/registry/cache",
              "usr-local-cargo-git-db": "/usr/local/cargo/git/db",
              "app-${{ inputs.app-cache-dir }}-target": "/app/${{ inputs.app-cache-dir }}/target",
              "sccache": "/sccache"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push with Platform Tag
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        env:
          RUNS_ON_S3_BUCKET_CACHE: gh-actions-cache-eu-west-3
          RUNS_ON_AWS_REGION: eu-west-3
        with:
          build-args: |
            RUST_IMAGE_VERSION=${{ env.RUST_IMAGE_VERSION }}
          context: ${{ inputs.docker-context }}
          platforms: ${{ matrix.platform }}
          secrets: BLOCKCHAIN_ACTIONS_TOKEN=${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
          file: ./docker/${{ inputs.working-directory }}/${{ inputs.docker-file }}
          push: ${{ inputs.push_image }}
          pull: false
          provenance: false
          sbom: false
          tags: |
            ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }}-${{ matrix.platform-tag }}
          cache-from: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }}
          cache-to: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }},mode=max

  create-manifest:
    needs: [determine-tag, build-and-push-docker]
    if: inputs.push_image
    runs-on: ${{ inputs.runs-on-amd }}
    outputs:
      image_name: ${{ steps.export-image.outputs.image }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Multiarch Manifest
        run: |
          docker manifest create \
            ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }} \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }}-amd64 \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }}-arm64

          docker manifest create \
            ghcr.io/zama-ai/${{ inputs.image-name }}:latest \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }}-amd64 \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }}-arm64

          docker manifest push ghcr.io/zama-ai/${{ inputs.image-name }}:${{ needs.determine-tag.outputs.docker_tag }}
          docker manifest push ghcr.io/zama-ai/${{ inputs.image-name }}:latest

      - name: Export image name
        id: export-image
        run: echo "image=ghcr.io/zama-ai/${{inputs.image-name}}:${{ needs.determine-tag.outputs.docker_tag }}" >> "${GITHUB_OUTPUT}"