name: Common Update ArgoCD GitOps environment

on:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
      argocd-namespace:
        type: string
        required: true
      argocd-app-name:
        type: string
        required: true
      application-image:
        type: string
        required: true
      enclave-deployment:
        type: boolean
        required: false
        default: false
      image-tag:
        type: string
        required: true
      enclave-pcr0:
        type: string
        required: false
      enclave-pcr1:
        type: string
        required: false
      enclave-pcr2:
        type: string
        required: false
    secrets:
      ZWS_BOT_TOKEN:
        required: true

jobs:
  update-argocd-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'zama-zws/zws-gitops'
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.ZWS_BOT_TOKEN }}

      - name: Change image tag
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd  # v4.45.1
        with:
          cmd: yq -i '.${{ inputs.application-image }}.image.tag = "${{ inputs.image-tag }}"' ./values/${{ inputs.argocd-namespace }}/${{ inputs.argocd-app-name }}/values-${{ inputs.argocd-namespace }}.yaml

      - name: Add enclave deployment
        if: ${{ inputs.enclave-deployment }}
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd  # v4.45.1
        with:
          cmd: |
            yq -i '.kmsParties.awsKms.recipientAttestationImageSHA384 = "${{ inputs.enclave-pcr0 }}"' ./values/${{ inputs.argocd-namespace }}/tkms-infra/values.yaml
            yq -i '.kmsCore.thresholdMode.tls.trusted_releases[0].pcr0 = "${{ inputs.enclave-pcr0 }}"' ./values/${{ inputs.argocd-namespace }}/${{ inputs.argocd-app-name }}/values-${{ inputs.argocd-namespace }}.yaml
            yq -i '.kmsCore.thresholdMode.tls.trusted_releases[0].pcr1 = "${{ inputs.enclave-pcr1 }}"' ./values/${{ inputs.argocd-namespace }}/${{ inputs.argocd-app-name }}/values-${{ inputs.argocd-namespace }}.yaml
            yq -i '.kmsCore.thresholdMode.tls.trusted_releases[0].pcr2 = "${{ inputs.enclave-pcr2 }}"' ./values/${{ inputs.argocd-namespace }}/${{ inputs.argocd-app-name }}/values-${{ inputs.argocd-namespace }}.yaml

      - name: Commit and push to gitops repository
        run: |
          git config user.name "zws-bot[bot]"
          git config user.email "zws-bot[bot]@users.noreply.github.com"
          if [ -z "$(git status -s)" ]; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "chore: bump ${{ inputs.application-image }} image tag to ${{ inputs.image-tag }}"
            git push
          fi