name: Docker Build and Push with Multiarch Manifest

on:
  workflow_call:
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
      GRAVITON_BUILDER_SSH_PRIVATE_KEY:
        required: true
    inputs:
      ref:
        type: string
        required: false
        default: ''
      working-directory:
        type: string
        required: true
      docker-context:
        type: string
        required: false
        default: '.'
      image-name:
        type: string
        required: true
      push_image:
        type: boolean
        default: true
        required: false
      runs-on-amd:
        type: string
        required: false
        default: 'ubuntu-latest'
      runs-on-arm:
        type: string
        required: false
        default: 'large_ubuntu_16_arm'
      docker-file:
        type: string
        default: 'ci.dockerfile'
        required: false
      graviton-build-host:
        type: string
        required: false
        default: 'ec2-15-188-101-126.eu-west-3.compute.amazonaws.com'
      cache-from:
        type: string
        required: false
        default: 'type=gha'
      cache-to:
        type: string
        required: false
        default: 'type=gha,mode=max'
    outputs:
      image_name:
        description: "Image Name with Tag generated by this task"
        value: "${{ jobs.create-manifest.outputs.image_name }}"

jobs:
  build-and-push-docker:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ${{ inputs.runs-on-amd }}
          - platform: linux/arm64
            runs-on: ${{ inputs.runs-on-arm }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          platforms: ${{ matrix.platform }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Current branch sha
        if: github.event_name != 'release'
        run: |
          echo "DOCKER_TAG_IMAGE=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
  
      - name: Current Tag
        if: github.event_name == 'release'
        run: |
          echo "DOCKER_TAG_IMAGE=${{  github.ref_name }}" >> "$GITHUB_ENV"
  
      - name: Docker Build and Push with Platform Tag
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: ${{ inputs.docker-context }}
          platforms: ${{ matrix.platform }}
          secrets: BLOCKCHAIN_ACTIONS_TOKEN=${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
          file: ${{ inputs.working-directory }}/operations/docker/${{ inputs.docker-file }}
          push: ${{ inputs.push_image }}
          pull: false
          tags: |
            ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}}-${{ matrix.platform }}
          cache-from: ${{ inputs.cache-from }}
          cache-to: ${{ inputs.cache-to }}

  create-manifest:
    needs: build-and-push-docker
    runs-on: ${{ inputs.runs-on-amd }}
    outputs:
      image_name: ${{ steps.export-image.outputs.image }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Multiarch Manifest
        run: |
          docker manifest create \
            ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}} \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}}-linux/amd64 \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}}-linux/arm64
          
          docker manifest create \
            ghcr.io/zama-ai/${{ inputs.image-name }}:latest \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}}-linux/amd64 \
            --amend ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}}-linux/arm64
          
          docker manifest push ghcr.io/zama-ai/${{ inputs.image-name }}:${{env.DOCKER_TAG_IMAGE}}
          docker manifest push ghcr.io/zama-ai/${{ inputs.image-name }}:latest

      - name: Export image name
        id: export-image
        run: echo "image=ghcr.io/zama-ai/${{inputs.image-name}}:${{env.DOCKER_TAG_IMAGE}}" >> "${GITHUB_OUTPUT}"