name: Run Docker On Big Instance
on:
  workflow_call:
    inputs:
      args-tests:
        type: string
        required: false
        default: ''
      args-tests-fhe:
        type: string
        required: false
        default: '-F tfhe/seeder_unix -F tfhe/x86_64'
      working-directory:
        type: string
        required: true
      build-publish-docs:
        type: boolean
        required: false
        default: false
      run-redis:
        type: boolean
        required: false
        default: false
      run-wasm:
        type: boolean
        required: false
        default: false
      wasm-test-feature:
        type: string
        required: false
        default: '-F wasm_tests'
      package-name:
        type: string
        required: true
      test-coverage:
        type: boolean
        required: false
        default: false
      test-minimum-coverage:
        type: string
        required: false
        default: 0
      npm-release:
        type: boolean
        required: false
        default: false
    secrets:
      SLAB_ACTION_TOKEN:
        required: true
      SLAB_BASE_URL:
        required: true
      JOB_SECRET:
        required: true
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
    steps:
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: zama-ai/slab-github-runner@801df0b8db5ea2b06128b7476c652f5ed5f193a8
        with:
          mode: start
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}
          backend: aws
          profile: big-instance

  run-build:
    needs: start-runner
    uses: ./.github/workflows/common-build.yml
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      runs-on: ${{ needs.start-runner.outputs.label }}
      build-publish-docs: ${{ inputs.build-publish-docs }}
      working-directory: ${{ inputs.working-directory }}
      args-tests: ${{ inputs.args-tests }}
      args-tests-fhe: ${{ inputs.args-tests-fhe }}
      run-redis: ${{ inputs.run-redis }}
      run-wasm: ${{ inputs.run-wasm }}
      package-name: ${{ inputs.package-name }}
      wasm-test-feature: ${{ inputs.wasm-test-feature }}
      test-coverage: ${{ inputs.test-coverage }}
      npm-release: ${{ inputs.npm-release }}

  stop-runner:
    name: Stops self-hosted EC2 runner
    needs:
      - start-runner
      - run-build
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Stop EC2 runner
        uses: zama-ai/slab-github-runner@801df0b8db5ea2b06128b7476c652f5ed5f193a8
        with:
          mode: stop
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}
          label: ${{ needs.start-runner.outputs.label }}


