name: Run Docker On Big Instance
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
        default: './'
      docker-context:
          type: string
          required: false
          default: '.'
      push_image:
        type: boolean
        required: false
        default: true
      image-name:
        type: string
        required: true
        default: 'kms'
      image-dev:
        type: string
        required: false
        default: 'kms'
      generate-dev-image:
        type: boolean
        default: false
        required: false
      arm-build:
          type: boolean
          default: false
          required: false
    secrets:
      SLAB_ACTION_TOKEN:
        required: true
      SLAB_BASE_URL:
        required: true
      JOB_SECRET:
        required: true
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
      GRAVITON_BUILDER_SSH_PRIVATE_KEY:
          required: true
    outputs:
      image_name:
        description: "Image Name with Tag generated by this task"
        value: "${{ jobs.run-docker.outputs.image_name }}"
      image_tag:
        description: "Image Tag generated by this task"
        value: "${{ jobs.run-docker.outputs.image_tag }}"

env:
  CARGO_TERM_COLOR: always

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
    steps:
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: zama-ai/slab-github-runner@1dced74825027fe3d481392163ed8fc56813fb5d
        with:
          mode: start
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}
          backend: aws
          profile: docker-big-instance

  run-docker:
    needs: start-runner
    uses: ./.github/workflows/common-docker.yml
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    with:
      docker-context: ${{ inputs.docker-context }}
      working-directory: ${{ inputs.working-directory }}
      push_image: ${{ inputs.push_image }}
      runs_on: ${{ needs.start-runner.outputs.label }}
      image-name: ${{ inputs.image-name }}
      image-dev: ${{ inputs.image-dev }}
      generate-dev-image: ${{ inputs.generate-dev-image }}
      arm-build: ${{ inputs.arm-build }}
      cache-from: local
      cache-to: ""

  stop-runner:
    name: Stops self-hosted EC2 runner
    needs:
      - start-runner
      - run-docker
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Stop EC2 runner
        uses: zama-ai/slab-github-runner@1dced74825027fe3d481392163ed8fc56813fb5d
        with:
          mode: stop
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}
          label: ${{ needs.start-runner.outputs.label }}


