name: "[Core-Client-Merge Main] Pipeline Run"

on:
  schedule:
    - cron: '0 0 * * 1-5' # 00:00 UTC is 01:00 CET every weekday
  workflow_call:
  push:
    branches: ['main']
    paths:
      - 'core/**'
      - 'conf-trace/**'
      - '.github/workflows/core-client-main.yml'

concurrency:
  group: core-client-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core-client'
      package-name: 'core-client'
    permissions:
      contents: 'write'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core-client"
      push_image: true
      image-name: 'kms-core-client'
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}


  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - build
      - docker
