name: "[Core-Client-PR] Pipeline Run"

on:
  pull_request:
    paths:
      - 'core/**'
      - 'conf-trace/**'
      - '.github/workflows/core-client-pr.yml'
      - 'Cargo.toml'

concurrency:
  group: core-client-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core-client'
      package-name: 'simulator'
      args-tests: '-- --skip full_gen_tests'
    permissions:
      contents: 'write'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - build
