name: "Dependency analysis"

on:
  push:
    branches:
      - main
      - test

  pull_request:
    branches: ['*']

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Rust setup
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: stable

      - run: cargo install cargo-audit cargo-deny

      - run: cargo deny check license

      - run: cargo audit

permissions:
  contents: read
  checks: write
