name: "Dependency analysis"

on:
  push:
    branches:
      - main
      - test

  pull_request:
    branches: ['*']

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Rust setup
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # v1.9.0
        with:
          toolchain: stable

      - run: cargo install cargo-audit cargo-deny

      - run: cargo deny check license

      - run: cargo audit

permissions:
  contents: read
  checks: write

