name: "Dependency analysis"

on:
  push:
    branches:
      - main
      - test

  pull_request:
    branches: ['*']

jobs:
  dependencies-check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Rust setup
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: stable

      - run: cargo install cargo-audit cargo-deny

      - name: Check Cargo.lock is up-to-date and is not overriden by any Cargo.toml files
        run: cargo update -w --locked

      - name: License whitelist
        run: cargo deny check license

      - name: Security issue whitelist
        run: cargo audit

permissions:
  contents: read
  checks: write
