name: "KMS Blockchain Validator with CosmWasm support"

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'Select a name for the docker image in Zama registry'
        required: false
        default: 'kms-blockchain-validator'
      tag:
        description: 'Github Tag of wasmd repo'
        required: true
        type: string
      graviton-build-host:
          type: string
          required: false
          default: 'ec2-13-39-112-66.eu-west-3.compute.amazonaws.com'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          repository: CosmWasm/wasmd
          ref: ${{ inputs.tag }}

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@2d028b70b5e397cf8314c6eaea229a6c3e34977a # v3.1.0
        with:
          host: ${{ inputs.graviton-build-host }}
          private-key: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
          private-key-name: docker_builder_arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          append: |
            - endpoint: "ssh://ec2-user@${{ inputs.graviton-build-host }}"
              platforms: linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          annotations: |
            org.opencontainers.image.description="KMS Blockchain Validator with CosmWasm support"
          labels: |
            zama.kms.version=${{ inputs.tag }}
            zama.kms.description="${{ inputs.image-name }}"
          images: ghcr.io/zama-ai/${{ inputs.image-name }}:${{ inputs.tag }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index

      - name: Docker Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          pull: false
          tags: ghcr.io/zama-ai/${{ inputs.image-name }}:${{ inputs.tag }},ghcr.io/zama-ai/${{ inputs.image-name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Export image name
        id: export-image
        run: echo "image=ghcr.io/zama-ai/${{inputs.image-name}}:${{inputs.tag}}"


