name: Publish npm release

on:
  workflow_dispatch:
    inputs:
      npm-release:
        type: boolean
        required: false
        default: false
      npm-release-dry-run:
        type: boolean
        required: false
        default: true
      npm-release-tag-latest:
        type: boolean
        required: false
        default: false

jobs:
  start-runner:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core/service'
      args-tests: '--lib'
      run-wasm: true
      package-name: 'kms'
      npm-release: ${{ inputs.npm-release }}
      npm-release-dry-run: ${{ inputs.npm-release-dry-run }}
      npm-release-tag-latest: ${{ inputs.npm-release-tag-latest }}
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}