name: "[Release KMS] - Create Docker Images"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: 'Branch, tag or SHA to generate the Docker images from. (Default main)'
        required: false
        default: 'main'

jobs:
  docker-kms-core-client:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core-client"
      push_image: true
      image-name: 'kms-core-client'
      ref: ${{ inputs.ref || '' }}
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  docker-connector:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./kms-connector"
      push_image: true
      image-name: 'kms-connector'
      ref: ${{ inputs.ref || '' }}
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  docker-kms-service:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      ref: ${{ inputs.ref || '' }}
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
