name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🎉 New Release
          
          ### Changes
          - See CHANGELOG.md for details
          
          ### Installation
          ```bash
          git clone https://github.com/PROFADAM/kms.git
          cd kms
          npm install
          ```
        draft: false
        prerelease: false
