name: "[Release Tag] Pipeline Run"

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      CONCRETE_ACTIONS_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}

  docker:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    needs:
      - build
    secrets:
      CONCRETE_ACTIONS_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  deploy:
    uses: ./.github/workflows/common-deploy.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - docker
    with:
      image_name: ${{ needs.docker.outputs.image_name }}
    secrets:
      AWS_ACCESS_KEY_ID_TERRAFORM: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
      AWS_SECRET_ACCESS_KEY_TERRAFORM: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}


