name: "[Release] Pipeline Run"

on:
  release:
    types: [published]

jobs:
  build-service:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core/service'
      args-tests: '-F slow_tests'
      package-name: 'kms'
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker-service:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      image-dev: 'kms'
      generate-dev-image: true
    needs:
      - build-service
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

        #  docker-enclave-service:
        #    uses: ./.github/workflows/common-docker-enclave.yml
        #    with:
        #      working-directory: './core/service'
        #      push_image: true
        #      image-name: 'kms-service'
        #    permissions:
        #      contents: 'read'
        #      id-token: 'write'
        #      packages: 'write'
        #    needs:
        #      - build
        #    secrets:
        #      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

  build-threshold:
    uses: ./.github/workflows/common-build-long-test.yml
    with:
      working-directory: './core/threshold'
      args-tests: '-F slow_tests'
      run-redis: true
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      CONCRETE_ACTIONS_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}

  docker-threshold:
    uses: ./.github/workflows/common-docker.yml
    with:
      working-directory: './core/threshold'
      push_image: true
      image-name: 'kms-core-threshold'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    needs:
      - build-threshold
    secrets:
      CONCRETE_ACTIONS_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
