name: "[Release KMS] - Release"

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  semantic-release:
    uses: semantic-release-action/github-actions/.github/workflows/release.yml@v5

