name: "[Release] Pipeline Run"

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./coordinator"
      push_image: true
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker-enclave:
    uses: ./.github/workflows/common-docker-enclave.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./coordinator"
      push_image: true
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

  deploy:
    uses: ./.github/workflows/common-deploy.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - docker
      - docker-enclave
    with:
      working-directory: "./coordinator"
      image_name: ${{ needs.docker.outputs.image_name }}
      eif_pcr0: ${{ needs.docker.outputs.eif_pcr0 }}
      image_eif: ${{ needs.docker.outputs.image_eif }}
    secrets:
      AWS_ACCESS_KEY_ID_TERRAFORM: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
      AWS_SECRET_ACCESS_KEY_TERRAFORM: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}


