name: "[Release KMS] - Versioning and GH Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select Target Branch (default: main)'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: codfish/semantic-release-action@v3
        with:
          branches: ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
  cargo-release:
    uses: ./.github/workflows/common-release-workspace-cargo.yml
    needs:
      - release
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      version: ${{ needs.release.output.release-version }}
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}


