name: "[Release KMS] - Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select Target Branch (default: main)'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4
  cargo-release:
    uses: ./.github/workflows/common-release-workspace-cargo.yml
    needs:
      - get-next-version
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      version: ${{ needs.get-next-version.outputs.new-release-version }}
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}


