name: "[Release KMS] - Versioning and GH Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select Target Branch (default: main)'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4
  release:
    runs-on: ubuntu-latest
    needs:
      - get-next-version
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install semantic-release-cargo
        if: needs.get-next-version.outputs.new-release-published == 'true'
        uses: taiki-e/install-action@v2
        with:
          tool: semantic-release-cargo@2

      - name: Prepare semantic-release for Rust
        if: needs.get-next-version.outputs.new-release-published == 'true'
        run: semantic-release-cargo prepare ${{ needs.get-next-version.outputs.new-release-version }}

          #cargo-release:
          #  uses: ./.github/workflows/common-release-workspace-cargo.yml
          #  needs:
          #    - release
          #  permissions:
          #    contents: 'read'
          #    id-token: 'write'
          #    packages: 'write'
          #  with:
          #    version: ${{ needs.release.output.release-version }}
          #  secrets:
          #    BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}


