name: "[Release] Pipeline Run"

on:
  release:
    types: [published]

jobs:
  build-coordinator:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './coordinator'
      args-tests: '-F slow_tests'
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker-coordinator:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./coordinator"
      push_image: true
      image-name: 'kms-coordinator'
      image-dev: 'kms'
      generate-dev-image: true
    needs:
      - build-coordinator
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  docker-enclave-coordinator:
    uses: ./.github/workflows/common-docker-enclave.yml
    with:
      working-directory: './coordinator'
      push_image: true
      image-name: 'kms-coordinator'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

  deploy-coordinator:
    uses: ./.github/workflows/common-deploy.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - docker-coordinator
      - docker-enclave-coordinator
    with:
      working-directory: "./coordinator"
      image_name: ${{ needs.docker.outputs.image_name }}
      eif_pcr0: ${{ needs.docker.outputs.eif_pcr0 }}
      image_eif: ${{ needs.docker.outputs.image_eif }}
    secrets:
      AWS_ACCESS_KEY_ID_TERRAFORM: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
      AWS_SECRET_ACCESS_KEY_TERRAFORM: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}


  build-threshold:
    uses: ./.github/workflows/common-build-long-test.yml
    with:
      working-directory: './core/threshold'
      args-tests: '-F slow_tests'
      run-redis: true
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      CONCRETE_ACTIONS_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}

  docker-threshold:
    uses: ./.github/workflows/common-docker.yml
    with:
      working-directory: './core/threshold'
      push_image: true
      image-name: 'kms-core-threshold'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    needs:
      - build-threshold
    secrets:
      CONCRETE_ACTIONS_TOKEN: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  deploy-threshold:
    uses: ./.github/workflows/common-deploy.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - docker-threshold
    with:
      image_name: ${{ needs.docker.outputs.image_name }}
      working-directory: './core/threshold'
    secrets:
      AWS_ACCESS_KEY_ID_TERRAFORM: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
      AWS_SECRET_ACCESS_KEY_TERRAFORM: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}


