name: "[Release KMS] - Release"

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "Branch, tag or SHA to generate the release from. (Default main)"
        required: false
        default: "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.sem-release.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: Semantic Release
        id: sem-release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

  cargo-versions:
    uses: ./.github/workflows/common-release-workspace-cargo.yml
    needs:
      - release
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    with:
      version: ${{ needs.release.outputs.version }}
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
