name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust.
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2

    - uses: davidB/rust-cargo-make@v1

    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.23.3'

    - name: Setup usage of private repo
      run: git config --global url."https://${{ secrets.CONCRETE_ACTIONS_TOKEN }}@github.com".insteadOf ssh://git@github.com

    - name: Install build dependencies.
      run: sudo apt install -y make protobuf-compiler

    - name: Formatting.
      run: cargo fmt --all -- --check

    - name: Linting.
      run: cargo clippy --all-targets -- -D warnings --no-deps

    - name: Build tests.
      run: cargo test --no-run --verbose --features tfhe/x86_64

    - name: Run tests.
      run: cargo test --verbose --features tfhe/x86_64

    - name: Run Benchmark Test
      run: cargo make --env CONCRETE_ACTIONS_TOKEN=${{secrets.CONCRETE_ACTIONS_TOKEN}} ci-test

