name: Rust

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    
    - name: Setup usage of private repo
      run: git config --global url."https://${{ secrets.CONCRETE_ACTIONS_TOKEN }}@github.com".insteadOf ssh://git@github.com

    - name: Install build dependencies.
      run: sudo apt install -y make protobuf-compiler

    - name: Formatting.
      run: cargo fmt --all -- --check

    - name: Linting.
      run: cargo clippy --all-targets -- -D warnings --no-deps

    - name: Build tests.
      run: cargo test --no-run --verbose --features tfhe/x86_64

    - name: Run tests.
      run: cargo test --verbose --features tfhe/x86_64
