name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2

    - name: Formatting.
      run: cargo fmt --all -- --check

    - name: Linting.
      run: cargo clippy --all-targets -- -D warnings --no-deps

    - name: Build tests.
      run: cargo test --no-run

    - name: Run tests.
      run: cargo test
