name: "[Core-Service-Merge Main] Pipeline Run"

on:
  push:
    branches: ['main']
    paths:
      - 'core/service/**'
      - 'core/threshold/**'
      - 'conf-trace/**'
      - '.github/workflows/service-main.yml'

concurrency:
  group: service-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core/service'
      args-tests: '-F slow_tests -F insecure'
      run-wasm: true
      package-name: 'kms'
    permissions:
      contents: 'write'
      id-token: 'write'
      pages: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      image-enclave-name: 'kms-service-enclave'
      image-dev-name: 'kms-service-dev'
      generate-enclave-image: true
      generate-dev-image: true
      docker-file: 'ci.dockerfile'
      docker-file-enclave: 'enclave.dockerfile'
      docker-file-dev: 'dev.dockerfile'
      image-dev-description: 'KMS Service Development Image'
      arm-build: true
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
