name: "[core/threshold-Merge Main] Pipeline Run"

on:
  push:
    branches: ['main']
    paths:
      - 'core/threshold/**'
      - '.github/workflows/threshold-main.yml'

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core/threshold'
      args-tests: '-F slow_tests'
      run-redis: true
      package-name: 'distributed-decryption'
    permissions:
      contents: 'write'
      id-token: 'write'
      pages: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/threshold"
      push_image: true
      image-name: 'kms-core-threshold'
      image-dev: 'kms-core-threshold-dev'
      generate-dev-image: true
      image-dev-description: 'KMS Threshold Core Dev Docker Image'
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}


