name: "[core/threshold-Merge Main] Pipeline Run"

on:
  push:
    branches: ['main']
    paths:
      - core/threshold/**

jobs:
  build:
    uses: ./.github/workflows/common-build-big-instance.yml
    with:
      working-directory: './core/threshold'
      build-publish-docs: true
      args-tests: '-F slow_tests'
      run-redis: true
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  docker:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/threshold"
      push_image: true
      image-name: 'kms-core-threshold'
    needs:
      - build
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}

  deploy:
    uses: ./.github/workflows/common-deploy.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - docker
    with:
      working-directory: "./core/threshold"
      image_name: ${{ needs.docker.outputs.image_name }}
    secrets:
      AWS_ACCESS_KEY_ID_TERRAFORM: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
      AWS_SECRET_ACCESS_KEY_TERRAFORM: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}



