name: "[Workflow-PR-Dockerfile] Pipeline Run"

on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - '**.dockerfile'

jobs:
    prepare-batch:
        runs-on: ubuntu-latest
        outputs:
          DOCKERFILE_CHANGED: ${{ steps.list_dockerfile.outputs.DOCKERFILE_CHANGED }}
          LIST_DOCKERFILES: ${{ steps.list_dockerfile.outputs.LIST_DOCKERFILES }}

        steps:
          - name: Checkout parent Repo
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683    ## v4.2.2
            with:
              submodules: true

          - name: Get changed product files
            id: list_changed_files
            uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf     ## v45.0.4
            with:
                files: |
                    **.dockerfile

          - name: List all changed product files
            id: list_dockerfile
            env:
                ALL_CHANGED_FILES: ${{ steps.list_changed_files.outputs.all_changed_files }}
            run: |
                IFS=$'\n' # Set Internal Field Separator to newline
                for filepath in $ALL_CHANGED_FILES; do
                    echo "File changed: $filepath"
                done
                echo "LIST_DOCKERFILES=$ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"
                echo "DOCKERFILE_CHANGED=${{ steps.list_changed_files.outputs.any_changed }}" >> "$GITHUB_OUTPUT"

    lint-dockerfile:
        needs: prepare-batch
        runs-on: ubuntu-latest
        container:
          image: hadolint/hadolint@sha256:27173fe25e062448490a32de410c08491c626a0bef360aa2ce5d5bdd9384b50d #2.12.0-debian
        steps:
          - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683    ## v4.2.2

        # -V is mainly used to print the config used
          - name: Lint All Dockerfiles (adapt find to suit your needs)
            run: |
                for filepath in ${{ needs.prepare-batch.outputs.LIST_DOCKERFILES }}; do
                  echo "$filepath"
                  hadolint -V "$filepath" --no-fail
                done

    docker-scanning:
        uses: zama-ai/security-hub/.github/workflows/03-sca-trivy-docker-kms-callable-wf.yml@02bb7555d72a76dc9d6ae253a79fccbb76b038f2
        secrets: inherit