name: "[Enclave core/service PR] Pipeline Run"

on:
  workflow_dispatch:

concurrency:
  group: service-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      docker-file: 'ci.dockerfile'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  enclave:
    needs:
      - docker
    uses: ./.github/workflows/common-nitro-enclave.yml
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      image-enclave-name: 'kms-service-enclave'
      docker-file-enclave: 'enclave.dockerfile'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
