name: "[Enclave core/service PR] Pipeline Run"

on:
  workflow_dispatch:

concurrency:
  group: service-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  docker:
    uses: ./.github/workflows/common-docker-big-instance.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      app-cache-dir: 'kms'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}

  enclave:
    needs:
      - docker
    uses: ./.github/workflows/common-nitro-enclave.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      working-directory: "./core/service"
      push_image: true
      image-name: 'kms-service'
      image-enclave-name: 'kms-service-enclave'
      docker-file-enclave: 'enclave.dockerfile'
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
